-- 1. CONTENT_BLOCKS (91)
insert into content_blocks (category_id, type, code, text) values
('community_management', 'pedagogical_objective', 'CM_OBJ_001', 'Comprendre le panorama des réseaux sociaux et le fonctionnement des algorithmes de diffusion.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_002', 'Savoir définir une stratégie social media adaptée à sa cible et à ses objectifs.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_003', 'Créer et programmer du contenu engageant sur les réseaux sociaux.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_004', 'Analyser les performances des publications et ajuster sa stratégie (KPI, reporting).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_005', 'Gérer une communauté en ligne (animation, engagement, modération).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_006', 'Optimiser son profil et sa page entreprise sur Instagram et Facebook.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_007', 'Créer des stories et des Reels pour Instagram.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_008', 'Mettre en place une publicité Facebook basique (Meta Ads).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_009', 'Optimiser son profil professionnel et la page entreprise sur LinkedIn.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_010', 'Utiliser Twitter/X pour la veille et la communication en temps réel.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_011', 'Construire et exploiter un calendrier éditorial multi-plateformes.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_012', 'Identifier les tendances et créer des vidéos courtes sur TikTok.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_013', 'Optimiser une chaîne YouTube (SEO vidéo et monétisation).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_014', 'Utiliser un outil de gestion multi-comptes (Hootsuite, Meta Business Suite) pour programmer ses publications.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_015', 'Mesurer les performances et identifier des axes d''amélioration à partir des KPI.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_016', 'Mettre en place une campagne de prospection ciblée avec LinkedIn Ads et Sales Navigator.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_017', 'Réaliser une veille concurrentielle sur LinkedIn et Twitter/X.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_018', 'Utiliser un outil de gestion multi-comptes B2B (Buffer, Hootsuite) pour la publication.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_019', 'Analyser des KPI B2B (leads générés, taux de conversion, engagement professionnel).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_020', 'Élaborer un plan d''action à 90 jours à partir d''un reporting LinkedIn.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_021', 'Créer et exploiter un calendrier éditorial TikTok orienté B2B.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_022', 'Mesurer la performance spécifique des formats vidéo courts (TikTok/Reels).'),
('community_management', 'pedagogical_objective', 'CM_OBJ_023', 'Mettre en œuvre une stratégie Community Management hybride combinant présentiel et distanciel.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_024', 'Rédiger un post LinkedIn optimisé et à forte valeur ajoutée.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_025', 'Réaliser un audit des réseaux sociaux existants, du site internet et de la fiche Google My Business d''une entreprise.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_026', 'Définir sa cible et ses personas pour adapter sa communication digitale.'),
('community_management', 'pedagogical_objective', 'CM_OBJ_027', 'Identifier et collaborer avec des influenceurs adaptés à sa stratégie de marque.'),
('community_management', 'skill', 'CM_SKILL_001', 'Élaboration d''une stratégie réseaux sociaux.'),
('community_management', 'skill', 'CM_SKILL_002', 'Animation et modération de communauté en ligne.'),
('community_management', 'skill', 'CM_SKILL_003', 'Création de contenus visuels avec Canva.'),
('community_management', 'skill', 'CM_SKILL_004', 'Maîtrise de Meta Business Suite (gestion Facebook/Instagram).'),
('community_management', 'skill', 'CM_SKILL_005', 'Maîtrise des outils de programmation multi-comptes (Hootsuite, Buffer).'),
('community_management', 'skill', 'CM_SKILL_006', 'Analyse de KPI et reporting social media.'),
('community_management', 'skill', 'CM_SKILL_007', 'Maîtrise de LinkedIn Ads et Sales Navigator (prospection B2B).'),
('community_management', 'positioning_question', 'CM_POS_001', 'Quelle formation souhaitez-vous suivre ?'),
('community_management', 'positioning_question', 'CM_POS_002', 'Quelle est votre situation professionnelle actuelle ? (Salarié·e / Entrepreneur / Demandeur d''emploi / Particulier)'),
('community_management', 'positioning_question', 'CM_POS_003', 'Quel est votre secteur d''activité ?'),
('community_management', 'positioning_question', 'CM_POS_004', 'Quelle est votre ancienneté dans le poste / l''entreprise ?'),
('community_management', 'positioning_question', 'CM_POS_005', 'Quel est votre niveau initial sur le sujet ? (Débutant / Intermédiaire / Avancé)'),
('community_management', 'positioning_question', 'CM_POS_006', 'Quelles sont vos attentes ? (Développer des compétences / Obtenir une certification / Autre)'),
('community_management', 'positioning_question', 'CM_POS_007', 'Quels sont vos objectifs concrets pour cette formation ?'),
('community_management', 'positioning_question', 'CM_POS_008', 'Quels sont les objectifs de votre entreprise pour cette formation ?'),
('community_management', 'positioning_question', 'CM_POS_009', 'Quels résultats attendez-vous à l''issue de la formation ?'),
('community_management', 'positioning_question', 'CM_POS_010', 'Quelles sont vos connaissances actuelles sur les réseaux sociaux ?'),
('community_management', 'positioning_question', 'CM_POS_011', 'Avez-vous déjà suivi une formation sur ce sujet ? Si oui, laquelle ?'),
('community_management', 'positioning_question', 'CM_POS_012', 'Quelle modalité préférez-vous ? (Présentiel / Distanciel / Hybride)'),
('community_management', 'positioning_question', 'CM_POS_013', 'Quelles sont vos disponibilités ?'),
('community_management', 'positioning_question', 'CM_POS_014', 'Quels supports préférez-vous ? (Vidéos / Exercices pratiques / Autres)'),
('community_management', 'positioning_question', 'CM_POS_015', 'Avez-vous des besoins spécifiques (santé, handicap) à signaler ?'),
('community_management', 'positioning_question', 'CM_POS_016', 'Souhaitez-vous être mis en contact avec le référent handicap ?'),
('community_management', 'positioning_question', 'CM_POS_017', 'Réalisation d''un audit / entretien diagnostic des réseaux sociaux existants, du site internet et de la fiche Google My Business.'),
('community_management', 'positioning_question', 'CM_POS_018', 'Quelles plateformes utilisez-vous actuellement ? (Instagram / Facebook / LinkedIn / TikTok / Twitter-X / YouTube / aucune)'),
('community_management', 'positioning_question', 'CM_POS_019', 'Quel est votre objectif prioritaire ? (Toucher le grand public B2C / Prospecter en B2B)'),
('community_management', 'evaluation_question', 'CM_EVAL_001', 'Quiz final Community Management en ligne (QCM), seuil de réussite : 70 %.'),
('community_management', 'evaluation_question', 'CM_EVAL_002', 'La formation a-t-elle répondu à vos attentes ? (Oui / Partiellement / Non)'),
('community_management', 'evaluation_question', 'CM_EVAL_003', 'Les objectifs pédagogiques étaient-ils clairs ?'),
('community_management', 'evaluation_question', 'CM_EVAL_004', 'Le formateur a-t-il su s''adapter à votre niveau ?'),
('community_management', 'evaluation_question', 'CM_EVAL_005', 'Quels points amélioreriez-vous ?'),
('community_management', 'evaluation_question', 'CM_EVAL_006', 'Étude de cas / production réelle de contenu (post, calendrier éditorial) évaluée par le formateur.'),
('community_management', 'evaluation_question', 'CM_EVAL_007', 'Jeu de rôle : simulation de réponse à un commentaire ou avis client sur les réseaux sociaux.'),
('community_management', 'evaluation_question', 'CM_EVAL_008', 'Évaluation du reporting LinkedIn et du plan d''action à 90 jours produits par l''apprenant (variante B2B).'),
('community_management', 'evaluation_question', 'CM_EVAL_009', 'Évaluation de la campagne sponsorisée LinkedIn créée en atelier (ciblage, budget, message).'),
('community_management', 'exercise', 'CM_EX_001', 'Créer un post Facebook et optimiser un profil Instagram (niveau débutant).'),
('community_management', 'exercise', 'CM_EX_002', 'Concevoir une story et un Reel Instagram sur un thème donné.'),
('community_management', 'exercise', 'CM_EX_003', 'Paramétrer une publicité Facebook basique (Meta Ads).'),
('community_management', 'exercise', 'CM_EX_004', 'Optimiser son profil LinkedIn et la page entreprise associée.'),
('community_management', 'exercise', 'CM_EX_005', 'Exercices de veille et de communication en temps réel sur Twitter/X.'),
('community_management', 'exercise', 'CM_EX_006', 'Créer des posts multi-plateformes et construire un calendrier éditorial.'),
('community_management', 'exercise', 'CM_EX_007', 'Créer une vidéo courte tendance pour TikTok.'),
('community_management', 'exercise', 'CM_EX_008', 'Optimiser une vidéo YouTube pour le référencement (SEO vidéo).'),
('community_management', 'exercise', 'CM_EX_009', 'Programmer une campagne de publications avec Hootsuite ou Meta Business Suite.'),
('community_management', 'exercise', 'CM_EX_010', 'Analyser les performances et les KPI d''un compte réseau social (étude de cas).'),
('community_management', 'exercise', 'CM_EX_011', 'Rédiger un post LinkedIn à valeur ajoutée (atelier B2B).'),
('community_management', 'exercise', 'CM_EX_012', 'Cibler et créer une campagne sponsorisée LinkedIn.'),
('community_management', 'exercise', 'CM_EX_013', 'Réaliser un reporting LinkedIn et un plan d''action à 90 jours.'),
('community_management', 'exercise', 'CM_EX_014', 'Cas pratique sectoriel : Instagram Reels pour promouvoir une destination touristique.'),
('community_management', 'exercise', 'CM_EX_015', 'Étude de cas d''entreprises + atelier création d''un calendrier éditorial TikTok (variante B2B).'),
('community_management', 'exercise', 'CM_EX_016', 'Atelier collaboratif Canva/Trello/Meta Business Suite en classe virtuelle + quiz gamifiés (variante hybride).'),
('community_management', 'exercise', 'CM_EX_017', 'Atelier CV / lettre de motivation avec Canva ou un outil de CV, simulation d''entretien (accompagnement socio-pro).'),
('community_management', 'method', 'CM_METHOD_001', 'Alternance d''apports théoriques, cas pratiques, mises en situation et ateliers collaboratifs.'),
('community_management', 'method', 'CM_METHOD_002', 'Supports variés : présentations interactives, vidéos pédagogiques, exercices en ligne, quiz, études de cas réels.'),
('community_management', 'method', 'CM_METHOD_003', 'Évaluations formatives en cours de formation (quiz, exercices pratiques).'),
('community_management', 'method', 'CM_METHOD_004', 'Évaluation sommative en fin de parcours (étude de cas, test, certification interne).'),
('community_management', 'method', 'CM_METHOD_005', 'Positionnement à l''entrée via entretien diagnostic / audit des réseaux sociaux existants.'),
('community_management', 'method', 'CM_METHOD_006', 'Modalité hybride combinant présentiel et classe virtuelle avec outils collaboratifs.'),
('community_management', 'need_example', 'CM_NEED_001', 'Développer sa présence sur LinkedIn pour toucher une clientèle B2B.'),
('community_management', 'need_example', 'CM_NEED_002', 'Améliorer la conversion des prospects en clients (leads → deals) via les réseaux sociaux.'),
('community_management', 'need_example', 'CM_NEED_003', 'Savoir créer et republier des contenus, sans maîtriser la stratégie ni les statistiques.'),
('community_management', 'need_example', 'CM_NEED_004', 'Travailler prioritairement sur LinkedIn plutôt que sur Facebook/Instagram (public professionnel).'),
('community_management', 'need_example', 'CM_NEED_005', 'Se former à un usage professionnel des réseaux sociaux pour la prospection et le reporting (salarié communication).'),
('community_management', 'need_example', 'CM_NEED_006', 'Créer du contenu authentique pour développer son activité en freelance / entrepreneuriat.');

-- 2. MODULES (12)
insert into modules (category_id, code, title, default_duration_hours, linked_objective_codes, source) values
('community_management', 'CM_MODULE_PANORAMA_ALGO', 'Panorama des réseaux sociaux, algorithmes et démarrage Facebook/Instagram', 7, ARRAY['CM_OBJ_001','CM_OBJ_006']::text[], NULL),
('community_management', 'CM_MODULE_STRATEGIE_INSTAGRAM', 'Stratégie de contenu Instagram, stories & Reels, publicité Facebook basique', 7, ARRAY['CM_OBJ_002','CM_OBJ_003','CM_OBJ_007','CM_OBJ_008']::text[], NULL),
('community_management', 'CM_MODULE_LINKEDIN_TWITTER', 'LinkedIn (profil + page entreprise), Twitter/X veille, exercices multi-plateformes', 7, ARRAY['CM_OBJ_009','CM_OBJ_010','CM_OBJ_011','CM_OBJ_024']::text[], NULL),
('community_management', 'CM_MODULE_TIKTOK_YOUTUBE', 'TikTok tendances & vidéos courtes, YouTube SEO/monétisation, atelier calendrier éditorial', 7, ARRAY['CM_OBJ_012','CM_OBJ_013']::text[], NULL),
('community_management', 'CM_MODULE_OUTILS_KPI', 'Outils de gestion (Hootsuite, Meta Business Suite), analyse des performances, synthèse + évaluation finale', 7, ARRAY['CM_OBJ_004','CM_OBJ_014','CM_OBJ_015']::text[], NULL),
('community_management', 'CM_MODULE_B2B_LINKEDIN_BASE', 'Panorama réseaux sociaux (accent B2B), optimisation LinkedIn, atelier rédaction de posts', 7, ARRAY['CM_OBJ_001','CM_OBJ_009','CM_OBJ_024']::text[], NULL),
('community_management', 'CM_MODULE_B2B_ADS_VEILLE', 'LinkedIn Ads & Sales Navigator, veille concurrentielle, atelier campagne sponsorisée', 7, ARRAY['CM_OBJ_016','CM_OBJ_017']::text[], NULL),
('community_management', 'CM_MODULE_B2B_REPORTING', 'Outils multi-comptes (Buffer/Hootsuite), analyse KPI B2B, atelier reporting + plan d''action 90j', 7, ARRAY['CM_OBJ_018','CM_OBJ_019','CM_OBJ_020']::text[], NULL),
('community_management', 'CM_MODULE_TIKTOK_B2B', 'TikTok et contenus vidéo courts pour le B2B', 3, ARRAY['CM_OBJ_021','CM_OBJ_022']::text[], 'veille métiers'),
('community_management', 'CM_MODULE_HYBRIDE', 'Community Management hybride (présentiel + distanciel)', 3, ARRAY['CM_OBJ_023']::text[], NULL),
('community_management', 'CM_MODULE_ACCOMPAGNEMENT_SOCIOPRO', 'Accompagnement socio-professionnel (CV, lettre de motivation, simulation d''entretien)', 1, ARRAY['CM_EX_017']::text[], NULL),
('community_management', 'CM_MODULE_AUDIT_DIAGNOSTIC', 'Audit / diagnostic des réseaux sociaux, site et fiche Google My Business existants', 1, ARRAY['CM_OBJ_025']::text[], NULL);

-- 3. QUESTION thématiques cochables + réponses
insert into questions (id, category_id, step, label, help_text, type, variable_key, display_condition, sort_order) values
('cm_themes', 'community_management', 'activite', 'Quels sujets seront abordés dans votre formation ?', 'Cochez tous les thèmes concernés : le logiciel construira automatiquement votre programme et vos documents à partir de ces choix.', 'multi_choice', 'cm_themes', '{"all":[{"variable":"training_category","operator":"equals","value":"community_management"}]}'::jsonb, 10);

insert into answer_options (question_id, value, label, sort_order) values
('cm_themes', 'stratégie_social_media', 'Stratégie social media', 1),
('cm_themes', 'definition_cible', 'Définition de la cible', 2),
('cm_themes', 'instagram', 'Instagram', 3),
('cm_themes', 'facebook', 'Facebook', 4),
('cm_themes', 'tiktok', 'TikTok', 5),
('cm_themes', 'linkedin', 'LinkedIn', 6),
('cm_themes', 'twitter_x', 'Twitter / X', 7),
('cm_themes', 'youtube', 'YouTube', 8),
('cm_themes', 'création_contenu', 'Création de contenu', 9),
('cm_themes', 'canva', 'Canva', 10),
('cm_themes', 'vidéo', 'Vidéo', 11),
('cm_themes', 'rédaction', 'Rédaction', 12),
('cm_themes', 'calendrier_éditorial', 'Calendrier éditorial', 13),
('cm_themes', 'programmation', 'Programmation / outils multi-comptes', 14),
('cm_themes', 'engagement', 'Engagement / animation de communauté', 15),
('cm_themes', 'publicité', 'Publicité (Ads)', 16),
('cm_themes', 'influence', 'Influence / marketing d''influence', 17),
('cm_themes', 'statistiques', 'Statistiques', 18),
('cm_themes', 'reporting', 'Reporting', 19),
('cm_themes', 'algorithmes', 'Algorithmes et fonctionnement des plateformes', 20),
('cm_themes', 'audit_diagnostic', 'Audit / diagnostic des réseaux existants', 21),
('cm_themes', 'accompagnement_sociopro', 'Accompagnement socio-professionnel', 22);

-- 4. RULES (35)
insert into rules (category_id, label, justification, conditions, actions, priority) values
('community_management', 'R001 - Socle transverse Community Management', 'Blocs méthode/évaluation communs à toute formation Community Management, quel que soit le thème choisi.', '{"all": [{"variable": "training_category", "operator": "equals", "value": "community_management"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_METHOD_001"}, {"type": "add_content_block", "code": "CM_METHOD_002"}, {"type": "add_content_block", "code": "CM_METHOD_003"}, {"type": "add_content_block", "code": "CM_METHOD_004"}, {"type": "add_content_block", "code": "CM_EVAL_002"}, {"type": "add_content_block", "code": "CM_EVAL_003"}, {"type": "add_content_block", "code": "CM_EVAL_004"}, {"type": "add_content_block", "code": "CM_EVAL_005"}]'::jsonb, 0),
('community_management', 'R002 - Stratégie social media', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "stratégie_social_media"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_001"}, {"type": "add_content_block", "code": "CM_OBJ_002"}, {"type": "add_module", "code": "CM_MODULE_PANORAMA_ALGO"}]'::jsonb, 0),
('community_management', 'R003 - Définition de la cible', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "definition_cible"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_026"}]'::jsonb, 0),
('community_management', 'R004 - Instagram', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "instagram"}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_STRATEGIE_INSTAGRAM"}, {"type": "add_content_block", "code": "CM_OBJ_006"}, {"type": "add_content_block", "code": "CM_OBJ_007"}, {"type": "add_content_block", "code": "CM_EX_001"}, {"type": "add_content_block", "code": "CM_EX_002"}]'::jsonb, 0),
('community_management', 'R005 - Facebook', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "facebook"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_006"}, {"type": "add_content_block", "code": "CM_OBJ_008"}, {"type": "add_content_block", "code": "CM_EX_003"}]'::jsonb, 0),
('community_management', 'R006a - TikTok (public généraliste)', 'Variante grand public : module TikTok/YouTube standard.', '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "tiktok"}, {"variable": "public_type", "operator": "not_in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_TIKTOK_YOUTUBE"}, {"type": "add_content_block", "code": "CM_OBJ_012"}, {"type": "add_content_block", "code": "CM_EX_007"}]'::jsonb, 0),
('community_management', 'R006b - TikTok (public B2B/salariés)', 'Variante B2B : module TikTok dédié, issu de la veille métiers (cf. R031).', '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "tiktok"}, {"variable": "public_type", "operator": "in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_TIKTOK_B2B"}, {"type": "add_content_block", "code": "CM_OBJ_021"}, {"type": "add_content_block", "code": "CM_OBJ_022"}, {"type": "add_content_block", "code": "CM_EX_015"}]'::jsonb, 0),
('community_management', 'R007 - LinkedIn', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "linkedin"}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_LINKEDIN_TWITTER"}, {"type": "add_content_block", "code": "CM_OBJ_009"}, {"type": "add_content_block", "code": "CM_OBJ_024"}, {"type": "add_content_block", "code": "CM_EX_004"}, {"type": "add_content_block", "code": "CM_EX_011"}]'::jsonb, 0),
('community_management', 'R008 - Twitter/X', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "twitter_x"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_010"}, {"type": "add_content_block", "code": "CM_EX_005"}]'::jsonb, 0),
('community_management', 'R009 - YouTube', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "youtube"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_013"}, {"type": "add_content_block", "code": "CM_EX_008"}]'::jsonb, 0),
('community_management', 'R010 - Création de contenu', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "création_contenu"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_003"}, {"type": "add_content_block", "code": "CM_SKILL_003"}]'::jsonb, 0),
('community_management', 'R011 - Canva', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "canva"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_SKILL_003"}]'::jsonb, 0),
('community_management', 'R012 - Vidéo', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "vidéo"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_007"}, {"type": "add_content_block", "code": "CM_EX_002"}]'::jsonb, 0),
('community_management', 'R013 - Rédaction', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "rédaction"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_024"}, {"type": "add_content_block", "code": "CM_EX_011"}]'::jsonb, 0),
('community_management', 'R014 - Calendrier éditorial', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "calendrier_éditorial"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_011"}, {"type": "add_content_block", "code": "CM_EX_006"}]'::jsonb, 0),
('community_management', 'R015 - Programmation / outils multi-comptes', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "programmation"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_014"}, {"type": "add_content_block", "code": "CM_SKILL_004"}, {"type": "add_content_block", "code": "CM_SKILL_005"}, {"type": "add_content_block", "code": "CM_EX_009"}]'::jsonb, 0),
('community_management', 'R016 - Engagement', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "engagement"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_SKILL_002"}, {"type": "add_content_block", "code": "CM_OBJ_005"}]'::jsonb, 0),
('community_management', 'R017a - Publicité (public généraliste)', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "publicité"}, {"variable": "public_type", "operator": "not_in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_008"}]'::jsonb, 0),
('community_management', 'R017b - Publicité / prospection B2B', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "publicité"}, {"variable": "public_type", "operator": "in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_016"}, {"type": "add_content_block", "code": "CM_SKILL_007"}, {"type": "add_content_block", "code": "CM_EX_012"}, {"type": "add_module", "code": "CM_MODULE_B2B_ADS_VEILLE"}]'::jsonb, 0),
('community_management', 'R018 - Influence', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "influence"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_027"}]'::jsonb, 0),
('community_management', 'R019 - Statistiques', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "statistiques"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_004"}, {"type": "add_content_block", "code": "CM_OBJ_015"}, {"type": "add_content_block", "code": "CM_SKILL_006"}]'::jsonb, 0),
('community_management', 'R020a - Reporting (public généraliste)', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "reporting"}, {"variable": "public_type", "operator": "not_in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_015"}, {"type": "add_module", "code": "CM_MODULE_OUTILS_KPI"}]'::jsonb, 0),
('community_management', 'R020b - Reporting (public B2B)', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "reporting"}, {"variable": "public_type", "operator": "in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_019"}, {"type": "add_content_block", "code": "CM_OBJ_020"}, {"type": "add_content_block", "code": "CM_EX_013"}, {"type": "add_content_block", "code": "CM_EVAL_008"}, {"type": "add_module", "code": "CM_MODULE_B2B_REPORTING"}]'::jsonb, 0),
('community_management', 'R021 - Algorithmes', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "algorithmes"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_001"}]'::jsonb, 0),
('community_management', 'R022 - Audit / diagnostic', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "audit_diagnostic"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_POS_017"}, {"type": "add_content_block", "code": "CM_OBJ_025"}, {"type": "add_module", "code": "CM_MODULE_AUDIT_DIAGNOSTIC"}]'::jsonb, 0),
('community_management', 'R023 - Accompagnement socio-professionnel', NULL, '{"all": [{"variable": "cm_themes", "operator": "contains", "value": "accompagnement_sociopro"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_EX_017"}, {"type": "add_module", "code": "CM_MODULE_ACCOMPAGNEMENT_SOCIOPRO"}]'::jsonb, 0),
('community_management', 'R024 - Variante B2B compacte (durée courte ou public pro)', 'Le contexte (durée réduite ou public salariés/entreprise) motive le passage en variante B2B compacte : LinkedIn devient le fil conducteur, TikTok/Instagram grand public sont retirés sauf choix explicite.', '{"any": [{"variable": "training_duration", "operator": "less_than_or_equal", "value": 21}, {"variable": "public_type", "operator": "in", "value": ["salaries", "entreprise", "b2b"]}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_B2B_LINKEDIN_BASE"}, {"type": "add_module", "code": "CM_MODULE_B2B_ADS_VEILLE"}, {"type": "add_module", "code": "CM_MODULE_B2B_REPORTING"}, {"type": "set_variable", "key": "cm_variant", "value": "b2b_compacte"}, {"type": "remove_module", "code": "CM_MODULE_TIKTOK_YOUTUBE"}, {"type": "remove_module", "code": "CM_MODULE_STRATEGIE_INSTAGRAM"}]'::jsonb, 10),
('community_management', 'R025 - Variante standard 5 jours (généraliste)', 'Public généraliste/particuliers avec durée longue : couverture multi-plateformes complète.', '{"all": [{"variable": "training_duration", "operator": "greater_than_or_equal", "value": 35}, {"variable": "public_type", "operator": "in", "value": ["generaliste", "particuliers"]}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_PANORAMA_ALGO"}, {"type": "add_module", "code": "CM_MODULE_STRATEGIE_INSTAGRAM"}, {"type": "add_module", "code": "CM_MODULE_LINKEDIN_TWITTER"}, {"type": "add_module", "code": "CM_MODULE_TIKTOK_YOUTUBE"}, {"type": "add_module", "code": "CM_MODULE_OUTILS_KPI"}, {"type": "set_variable", "key": "cm_variant", "value": "standard_5j"}]'::jsonb, 10),
('community_management', 'R026 - Secteur tourisme', 'Remplace un exercice générique par un cas pratique sectoriel tourisme.', '{"all": [{"variable": "sector", "operator": "equals", "value": "tourisme"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_EX_014"}]'::jsonb, 0),
('community_management', 'R027a - Niveau débutant', 'Priorise les blocs fondamentaux (algorithmes, bases Instagram/Facebook) déjà ajoutés par les autres règles — ne crée pas de nouveau contenu, ajuste la priorité d''affichage.', '{"all": [{"variable": "entry_level", "operator": "equals", "value": "debutant"}]}'::jsonb, '[{"type": "set_variable", "key": "cm_priority_focus", "value": "fondamentaux"}]'::jsonb, 0),
('community_management', 'R027b - Niveau avancé', NULL, '{"all": [{"variable": "entry_level", "operator": "equals", "value": "avance"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_OBJ_016"}]'::jsonb, 0),
('community_management', 'R028 - Profil freelance / entrepreneur', 'Priorise contenu authentique et prospection pour un public freelance/entrepreneur.', '{"all": [{"variable": "beneficiary_profile", "operator": "equals", "value": "freelance_entrepreneur"}]}'::jsonb, '[{"type": "add_content_block", "code": "CM_NEED_006"}]'::jsonb, 0),
('community_management', 'R029 - Profil salarié en communication', 'Priorise reporting/KPI/multi-comptes (déjà couverts par les thèmes correspondants) — marque la priorité sans dupliquer le contenu.', '{"all": [{"variable": "beneficiary_profile", "operator": "equals", "value": "salarie_communication"}]}'::jsonb, '[{"type": "set_variable", "key": "cm_priority_focus", "value": "reporting_kpi"}]'::jsonb, 0),
('community_management', 'R030 - Modalité hybride', NULL, '{"all": [{"variable": "training_method", "operator": "equals", "value": "hybride"}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_HYBRIDE"}, {"type": "add_content_block", "code": "CM_METHOD_006"}]'::jsonb, 0),
('community_management', 'R031 - Module TikTok B2B activé par la veille', 'Illustration du mécanisme veille → règle : ce module a été ajouté suite à une fiche de veille métiers validée en back-office, indépendamment de la variante choisie.', '{"all": [{"variable": "admin_flag_veille_tiktok_b2b", "operator": "is_true", "value": true}]}'::jsonb, '[{"type": "add_module", "code": "CM_MODULE_TIKTOK_B2B"}]'::jsonb, 5);
