-- Migration 0009 : 15 documents transverses (critères 4-7, indicateurs 12, 18-32)
-- Générée programmatiquement depuis banque-procedures-transverses.md (cf. journal-avancement.md).

insert into document_templates (id, label, category_scope, applicable_when, linked_indicator_numbers, folder_group, sort_order, is_active) values
('organigramme_fiches_poste', 'Organigramme fonctionnel et fiches de poste', 'all', '{}'::jsonb, ARRAY[18], '06_Procedures', 10, true),
('procedure_selection_intervenants', 'Procédure de sélection des intervenants', 'all', '{}'::jsonb, ARRAY[21], '06_Procedures', 20, true),
('plan_developpement_competences', 'Plan de développement des compétences', 'all', '{}'::jsonb, ARRAY[22], '06_Procedures', 30, true),
('procedure_veille_legale', 'Procédure de veille légale et réglementaire', 'all', '{}'::jsonb, ARRAY[23], '07_Veille', 40, true),
('procedure_veille_metiers', 'Procédure de veille métiers et compétences', 'all', '{}'::jsonb, ARRAY[24], '07_Veille', 50, true),
('procedure_veille_pedagogique', 'Procédure de veille pédagogique et technologique', 'all', '{}'::jsonb, ARRAY[25], '07_Veille', 60, true),
('procedure_accompagnement_psh', 'Procédure d''accompagnement des personnes en situation de handicap', 'all', '{}'::jsonb, ARRAY[26], '06_Procedures', 70, true),
('procedure_selection_sous_traitants', 'Procédure de sélection et de suivi des sous-traitants', 'all', '{}'::jsonb, ARRAY[27], '06_Procedures', 80, true),
('procedure_mobilisation_partenaires', 'Procédure de mobilisation des partenaires socio-économiques', 'all', '{}'::jsonb, ARRAY[28], '06_Procedures', 90, true),
('procedure_accompagnement_insertion', 'Procédure d''accompagnement à l''insertion professionnelle et à la poursuite d''études', 'all', '{}'::jsonb, ARRAY[29], '06_Procedures', 100, true),
('procedure_recueil_appreciations', 'Procédure de recueil des appréciations des parties prenantes', 'all', '{}'::jsonb, ARRAY[30], '08_Amelioration', 110, true),
('procedure_reclamations', 'Procédure de traitement des réclamations', 'all', '{}'::jsonb, ARRAY[31], '08_Amelioration', 120, true),
('procedure_amelioration_continue', 'Procédure d''amélioration continue', 'all', '{}'::jsonb, ARRAY[32], '08_Amelioration', 130, true),
('procedure_anti_abandon', 'Procédure de prévention des absences et abandons', 'all', '{}'::jsonb, ARRAY[12], '06_Procedures', 140, true),
('charte_engagement_assiduite', 'Charte d''engagement — Assiduité et présence', 'all', '{}'::jsonb, ARRAY[12], '03_Avant_formation', 150, true);

insert into document_template_sections (document_template_id, code, title, sort_order, content_type, html_template, source_content_block_type, content_block_scope) values
('organigramme_fiches_poste', 'organigramme_table', 'Organigramme fonctionnel', 1, 'rich_text', '<table><thead><tr><th>Fonction</th><th>Responsable</th><th>Missions principales</th></tr></thead><tbody>
<tr><td>Direction / Gestion</td><td>{{director_name}}</td><td>Stratégie, gestion administrative et financière, relation avec les financeurs</td></tr>
<tr><td>Pédagogique</td><td>{{pedagogical_referent_name}}</td><td>Conception et animation des formations, suivi pédagogique des stagiaires</td></tr>
<tr><td>Administratif</td><td>{{administrative_referent_name}}</td><td>Gestion des dossiers, convocations, conventions, suivi des financements</td></tr>
<tr><td>Référent Handicap</td><td>{{disability_referent_name}}</td><td>Accueil et accompagnement des PSH, adaptation des parcours</td></tr>
<tr><td>Commercial / Communication</td><td>{{director_name}}</td><td>Promotion des formations, prospection, suivi des clients</td></tr>
<tr><td>Technique / Digital</td><td>{{technical_provider_name}}</td><td>Outils numériques, plateformes e-learning, assistance technique</td></tr>
</tbody></table>
<p>{{sole_practitioner_note}}</p>', null, 'global'),
('organigramme_fiches_poste', 'referents_contacts', 'Référents et intervenants', 2, 'rich_text', '<p><strong>Référents internes :</strong></p>
<ul>
<li>Référent pédagogique : {{pedagogical_referent_name}} — {{pedagogical_referent_email}} / {{pedagogical_referent_phone}}</li>
<li>Référent administratif : {{administrative_referent_name}} — {{administrative_referent_email}} / {{administrative_referent_phone}}</li>
<li>Référent handicap : {{disability_referent_name}} — {{disability_referent_email}} / {{disability_referent_phone}}</li>
</ul>
<p><strong>Intervenants externes (si applicable) :</strong></p>
<ul>
<li>Formateur·trice en {{external_trainer_discipline}} : {{external_trainer_name}}, {{external_trainer_contract_type}}</li>
<li>Prestataire technique (si FOAD / visio) : {{technical_provider_name}}, {{technical_provider_company}}</li>
</ul>', null, 'global'),
('organigramme_fiches_poste', 'fiches_de_poste', 'Fiches de poste de référence', 3, 'content_block_list', null, 'job_description', 'global'),
('procedure_selection_intervenants', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de sélection et d''évaluation des intervenants<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_selection_intervenants', 'objectif', 'Objectif', 2, 'rich_text', '<p>Garantir que les intervenants mobilisés par {{company_name}} disposent des compétences pédagogiques, techniques et professionnelles adaptées aux prestations de formation proposées.</p>', null, 'global'),
('procedure_selection_intervenants', 'champ_application', 'Champ d''application', 3, 'rich_text', '<p>Tous les formateurs internes, vacataires et prestataires externes intervenant dans les formations de {{company_name}}.</p>', null, 'global'),
('procedure_selection_intervenants', 'processus_selection', 'Processus de sélection', 4, 'rich_text', '<ol>
<li>Analyse du besoin : identification des compétences requises par formation ; référence aux programmes publiés sur {{company_website}}.</li>
<li>Sourcing : publication d''une annonce ou recherche via réseau professionnel ; pré-sélection sur CV, diplômes, expériences et certifications.</li>
<li>Entretien de recrutement : entretien pédagogique et technique avec grille d''évaluation standardisée ; mise en situation (exercice pédagogique ou cas pratique).</li>
<li>Décision de recrutement : validation par la Direction pédagogique ; signature d''un contrat de travail ou de prestation de service.</li>
</ol>', null, 'global'),
('procedure_selection_intervenants', 'evaluation_continue', 'Évaluation continue', 5, 'rich_text', '<ul><li>Entretiens annuels avec auto-évaluation et retour qualité.</li><li>Analyse des questionnaires de satisfaction apprenants (≥ {{trainer_satisfaction_rate_target}} de satisfaction attendu).</li><li>Mises à jour régulières des compétences (plan de développement des compétences).</li></ul>', null, 'global'),
('procedure_selection_intervenants', 'archivage', 'Archivage', 6, 'rich_text', '<p>Tous les documents (CV, diplômes, grille d''entretien, contrats) sont conservés {{archiving_duration_trainer_docs}} dans le dossier RH de l''intervenant.</p>', null, 'global'),
('procedure_selection_intervenants', 'grille_entretien', 'Grille d''entretien (à remplir)', 7, 'rich_text', '<p>Nom du candidat : …………………… &nbsp; Poste visé : …………………… &nbsp; Date : …………………… &nbsp; Évaluateur : ……………………</p>
<table><thead><tr><th>Critère</th><th>Éléments observés</th><th>Note (1 à 5)</th><th>Commentaires</th></tr></thead><tbody>
<tr><td>Compétences techniques</td><td>Maîtrise du domaine</td><td></td><td></td></tr>
<tr><td>Compétences pédagogiques</td><td>Capacité à transmettre, structurer, adapter au public</td><td></td><td></td></tr>
<tr><td>Méthodes pédagogiques</td><td>Connaissance des outils (e-learning, cas pratiques...)</td><td></td><td></td></tr>
<tr><td>Expérience professionnelle</td><td>Années d''expérience, références, projets menés</td><td></td><td></td></tr>
<tr><td>Gestion de groupe</td><td>Capacité d''animation, écoute, gestion des situations difficiles</td><td></td><td></td></tr>
<tr><td>Adaptabilité</td><td>Prise en compte des publics spécifiques (PSH, niveaux hétérogènes)</td><td></td><td></td></tr>
<tr><td>Langues (si pertinent)</td><td>Niveau certifié</td><td></td><td></td></tr>
</tbody></table>
<p>Décision : ☐ Retenu(e) ☐ À revoir ☐ Non retenu(e)</p>', null, 'global'),
('procedure_selection_intervenants', 'tableau_correspondance_competences', 'Compétences requises par domaine', 8, 'content_block_list', null, 'required_skill', 'global'),
('plan_developpement_competences', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Période : {{plan_period}}<br/>Version : {{procedure_version}}</p>', null, 'global'),
('plan_developpement_competences', 'objectifs_plan', 'Objectifs du plan', 2, 'rich_text', '<ul><li>Garantir la mise à jour et l''évolution des compétences des salariés et formateurs.</li><li>Adapter les compétences aux évolutions pédagogiques, technologiques et réglementaires.</li><li>Favoriser la professionnalisation continue et l''attractivité de l''organisme.</li></ul>', null, 'global'),
('plan_developpement_competences', 'methodologie', 'Méthodologie', 3, 'rich_text', '<ul><li>Recueil des besoins via entretiens professionnels annuels.</li><li>Analyse des besoins stratégiques en lien avec les formations proposées.</li><li>Validation par la Direction et intégration dans un plan global.</li></ul>', null, 'global'),
('plan_developpement_competences', 'axes_prioritaires', 'Axes prioritaires', 4, 'content_block_list', null, 'training_axis', 'global'),
('plan_developpement_competences', 'budget_previsionnel', 'Budget prévisionnel', 5, 'rich_text', '<p>{{training_budget_percent_payroll}} de la masse salariale consacrée à la formation.</p>', null, 'global'),
('plan_developpement_competences', 'suivi_evaluation', 'Suivi et évaluation', 6, 'rich_text', '<ul><li>Mise à jour du plan chaque année.</li><li>Tableaux de suivi par salarié.</li><li>Évaluation de l''impact via questionnaires internes et analyse qualité.</li></ul>', null, 'global'),
('plan_developpement_competences', 'grille_entretien_professionnel', 'Grille d''entretien professionnel (à remplir)', 7, 'rich_text', '<p>Nom du salarié : …………………… &nbsp; Poste : …………………… &nbsp; Date : …………………… &nbsp; Évaluateur : ……………………</p>
<ol>
<li>Parcours et missions — principales activités réalisées / points forts / difficultés rencontrées</li>
<li>Compétences actuelles — techniques / pédagogiques / transversales</li>
<li>Besoins et souhaits de formation — liés au poste / aux évolutions métiers / souhaits personnels</li>
<li>Plan d''action — formation(s) envisagée(s), modalités, période, validation ☐ Oui ☐ Non</li>
</ol>', null, 'global'),
('plan_developpement_competences', 'tableau_suivi_formations', 'Tableau de suivi des formations réalisées', 8, 'rich_text', '<table><thead><tr><th>Salarié / Formateur</th><th>Poste</th><th>Formation suivie</th><th>Date</th><th>Modalité</th><th>Organisme formateur</th><th>Satisfaction</th><th>Impact observé</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_veille_legale', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de veille légale et réglementaire<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_veille_legale', 'objectif', 'Objectif', 2, 'rich_text', '<p>Assurer une veille régulière sur les évolutions légales, réglementaires et institutionnelles relatives à la formation professionnelle en {{region}}, et adapter les pratiques de {{company_name}} en conséquence.</p>', null, 'global'),
('procedure_veille_legale', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Qualité ({{quality_referent_name}}) : coordination de la veille.</li><li>Direction : validation des actions correctives.</li><li>Formateurs : application des ajustements pédagogiques.</li></ul>', null, 'global'),
('procedure_veille_legale', 'sources_principales', 'Sources principales', 4, 'content_block_list', null, 'watch_source_legal', 'global'),
('procedure_veille_legale', 'processus', 'Processus', 5, 'rich_text', '<ol><li>Collecte {{watch_collect_frequency}} par la Référente Qualité.</li><li>Analyse des impacts possibles sur l''organisme.</li><li>Diffusion interne via note ou mail.</li><li>Mise à jour des documents internes (CGV, conventions, livrets d''accueil).</li><li>Archivage : tableau de suivi et copies des sources conservés {{archiving_duration}}.</li></ol>', null, 'global'),
('procedure_veille_legale', 'evaluation', 'Évaluation', 6, 'rich_text', '<p>Une vérification est réalisée {{watch_review_frequency}} en réunion qualité.</p>', null, 'global'),
('procedure_veille_legale', 'registre_veille', 'Registre de veille (structure)', 7, 'rich_text', '<table><thead><tr><th>Date</th><th>Source consultée</th><th>Thème / évolution</th><th>Impact identifié</th><th>Action mise en place</th><th>Responsable</th><th>État</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_veille_legale', 'exemples_veille', 'Exemples d''entrées (illustratif)', 8, 'content_block_list', null, 'watch_example', 'global'),
('procedure_veille_metiers', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de veille métiers et compétences<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_veille_metiers', 'objectif', 'Objectif', 2, 'rich_text', '<p>Identifier et exploiter les évolutions des métiers, des compétences et des emplois liés aux domaines de formation proposés par {{company_name}} pour adapter en continu l''offre de formation.</p>', null, 'global'),
('procedure_veille_metiers', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Qualité ({{quality_referent_name}}) : coordination de la veille.</li><li>Référents pédagogiques : analyse des évolutions et mise à jour des contenus.</li><li>Formateurs : contribution via retours d''expérience et suivi terrain.</li></ul>', null, 'global'),
('procedure_veille_metiers', 'sources_principales', 'Sources principales', 4, 'content_block_list', null, 'watch_source_metiers', 'global'),
('procedure_veille_metiers', 'processus', 'Processus', 5, 'rich_text', '<ol><li>Collecte des informations ({{watch_collect_frequency}}).</li><li>Analyse des impacts sur nos formations.</li><li>Diffusion interne (note ou mail).</li><li>Mise à jour des programmes si nécessaire.</li><li>Archivage des résultats dans le tableau de veille.</li></ol>', null, 'global'),
('procedure_veille_metiers', 'evaluation', 'Évaluation', 6, 'rich_text', '<p>La veille est vérifiée {{watch_review_frequency}} en réunion qualité.</p>', null, 'global'),
('procedure_veille_metiers', 'registre_veille', 'Registre de veille (structure)', 7, 'rich_text', '<table><thead><tr><th>Date</th><th>Source consultée</th><th>Thème / évolution</th><th>Impact identifié</th><th>Action mise en place</th><th>Responsable</th><th>État</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_veille_metiers', 'exemple_adaptation_programme', 'Exemple d''adaptation de programme (illustratif)', 8, 'content_block_list', null, 'program_adaptation_example', 'global'),
('procedure_veille_pedagogique', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de veille pédagogique et technologique<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_veille_pedagogique', 'objectif', 'Objectif', 2, 'rich_text', '<p>Assurer une veille régulière sur les innovations pédagogiques et technologiques afin d''adapter les méthodes et outils de formation de {{company_name}} aux évolutions du secteur.</p>', null, 'global'),
('procedure_veille_pedagogique', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Qualité ({{quality_referent_name}}) : coordination de la veille.</li><li>Référents pédagogiques : analyse des innovations et propositions d''intégration.</li><li>Formateurs : expérimentation et remontée terrain.</li></ul>', null, 'global'),
('procedure_veille_pedagogique', 'sources_principales', 'Sources principales', 4, 'content_block_list', null, 'watch_source_pedagogical', 'global'),
('procedure_veille_pedagogique', 'processus', 'Processus', 5, 'rich_text', '<ol><li>Collecte {{watch_collect_frequency}} par la Référente Qualité.</li><li>Analyse des innovations identifiées.</li><li>Diffusion via note interne.</li><li>Expérimentation dans un module pilote.</li><li>Intégration dans les formations si résultats positifs.</li></ol>', null, 'global'),
('procedure_veille_pedagogique', 'archivage', 'Archivage', 6, 'rich_text', '<p>Toutes les traces de veille sont archivées {{archiving_duration}} dans le dossier « Veille Pédagogique ».</p>', null, 'global'),
('procedure_veille_pedagogique', 'registre_veille', 'Registre de veille (structure)', 7, 'rich_text', '<table><thead><tr><th>Date</th><th>Source consultée</th><th>Innovation identifiée</th><th>Impact potentiel</th><th>Action décidée</th><th>Responsable</th><th>État</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_veille_pedagogique', 'innovations', 'Innovations pédagogiques suivies', 8, 'content_block_list', null, 'pedagogical_innovation', 'global'),
('procedure_veille_pedagogique', 'exemple_adaptation', 'Exemple d''adaptation pédagogique (illustratif)', 9, 'content_block_list', null, 'program_adaptation_example', 'global'),
('procedure_accompagnement_psh', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure d''accueil et d''accompagnement des publics en situation de handicap (PSH)<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_accompagnement_psh', 'objectif', 'Objectif', 2, 'rich_text', '<p>Assurer un accueil inclusif et garantir l''accessibilité des formations pour toute personne en situation de handicap.</p>', null, 'global'),
('procedure_accompagnement_psh', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Handicap : {{disability_referent_name}} — {{disability_referent_email}} / {{disability_referent_phone}}.</li><li>Direction pédagogique : validation des aménagements.</li><li>Formateurs : mise en œuvre concrète des adaptations.</li></ul>', null, 'global'),
('procedure_accompagnement_psh', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Identification : recueil des besoins spécifiques lors de l''inscription.</li><li>Analyse : entretien individuel confidentiel avec la Référente Handicap.</li><li>Orientation : mise en relation avec des partenaires spécialisés.</li><li>Adaptation : supports adaptés (polices lisibles, sous-titrage vidéos, temps supplémentaire, accessibilité numérique).</li><li>Suivi : point régulier pendant la formation et bilan en fin de parcours.</li></ol>', null, 'global'),
('procedure_accompagnement_psh', 'ressources', 'Partenaires ressources', 5, 'content_block_list', null, 'partner_disability', 'global'),
('procedure_accompagnement_psh', 'archivage', 'Archivage', 6, 'rich_text', '<p>Chaque demande d''aménagement est documentée et conservée {{archiving_duration}}.</p>', null, 'global'),
('procedure_accompagnement_psh', 'charte_accessibilite', 'Charte d''engagement accessibilité', 7, 'content_block_list', null, 'commitment_text', 'global'),
('procedure_selection_sous_traitants', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de sélection et de suivi des sous-traitants<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_selection_sous_traitants', 'objectif', 'Objectif', 2, 'rich_text', '<p>Garantir que toute prestation confiée à un sous-traitant respecte les exigences Qualiopi et le référentiel national qualité.</p>', null, 'global'),
('procedure_selection_sous_traitants', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Direction pédagogique : sélection et validation des sous-traitants.</li><li>Référente Qualité : contrôle documentaire et suivi des engagements.</li></ul>', null, 'global'),
('procedure_selection_sous_traitants', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Identification du besoin : expertise manquante ou besoin ponctuel.</li><li>Sélection : examen des candidatures selon une grille (CV, diplômes, certifications, références).</li><li>Contrat de sous-traitance : signature obligatoire avant toute mission.</li><li>Intégration : présentation des procédures internes (Qualiopi, livret intervenant).</li><li>Suivi : évaluation régulière (questionnaires apprenants, observation, retour qualité).</li><li>Archivage : conservation des contrats et preuves de conformité pendant {{archiving_duration}}.</li></ol>', null, 'global'),
('procedure_selection_sous_traitants', 'tableau_suivi_conformite', 'Tableau de suivi de conformité', 5, 'rich_text', '<table><thead><tr><th>Nom du sous-traitant</th><th>Formation concernée</th><th>CV &amp; diplômes reçus</th><th>Contrat signé</th><th>Références vérifiées</th><th>Suivi qualité</th><th>Conforme</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_selection_sous_traitants', 'charte_qualite_sous_traitants', 'Charte qualité sous-traitants', 6, 'content_block_list', null, 'commitment_text', 'global'),
('procedure_selection_sous_traitants', 'contrat_sous_traitance', 'Trame de contrat de sous-traitance', 7, 'content_block_list', null, 'legal_clause', 'global'),
('procedure_mobilisation_partenaires', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de mobilisation des partenaires socio-économiques<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_mobilisation_partenaires', 'objectif', 'Objectif', 2, 'rich_text', '<p>Assurer la mobilisation et le suivi de partenaires socio-économiques afin de garantir l''accueil des apprenants en entreprise et la coconstruction des parcours de formation.</p>', null, 'global'),
('procedure_mobilisation_partenaires', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Direction pédagogique : identification et validation des partenariats.</li><li>Formateurs référents : suivi pédagogique en entreprise.</li><li>Référente Qualité : traçabilité et archivage des conventions.</li></ul>', null, 'global'),
('procedure_mobilisation_partenaires', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Prospection : identification des entreprises locales (en {{region}}) correspondant aux secteurs de formation.</li><li>Convention : signature d''une convention de stage/partenariat.</li><li>Coconstruction : définition des missions et objectifs pédagogiques avec l''entreprise d''accueil.</li><li>Suivi : échanges réguliers (visites, appels, mails) et livret de liaison apprenant-entreprise.</li><li>Évaluation : recueil des retours d''expérience (apprenants + tuteurs).</li><li>Amélioration continue : intégration des feedbacks dans les programmes de formation.</li></ol>', null, 'global'),
('procedure_mobilisation_partenaires', 'convention_partenariat', 'Trame de convention de partenariat', 5, 'content_block_list', null, 'legal_clause', 'global'),
('procedure_accompagnement_insertion', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure d''accompagnement à l''insertion professionnelle et à la poursuite d''études<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_accompagnement_insertion', 'objectif', 'Objectif', 2, 'rich_text', '<p>Accompagner les apprenants de {{company_name}} vers l''emploi, l''alternance ou la poursuite d''études en renforçant leur employabilité et en facilitant leur orientation.</p>', null, 'global'),
('procedure_accompagnement_insertion', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Direction pédagogique : coordination des actions.</li><li>Référente Qualité : suivi et traçabilité.</li><li>Formateurs : participation aux ateliers (CV, simulation entretien, orientation).</li></ul>', null, 'global'),
('procedure_accompagnement_insertion', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Analyse des besoins : identification des projets professionnels en début de formation.</li><li>Ateliers insertion : CV, lettres de motivation, simulations d''entretiens.</li><li>Diffusion d''offres : opportunités d''emploi/stage via mailing et plateforme interne.</li><li>Partenariats : mobilisation de partenaires locaux (emploi, insertion PSH).</li><li>Orientation : information sur les suites de parcours (RNCP, équivalences, passerelles).</li><li>Suivi : enquête d''insertion {{insertion_survey_delay}}.</li></ol>', null, 'global'),
('procedure_accompagnement_insertion', 'planning_type_insertion', 'Planning type (à répartir sur la durée de la formation)', 5, 'rich_text', '<table><thead><tr><th>Étape</th><th>Action</th><th>Objectif</th></tr></thead><tbody>
<tr><td>Début de parcours</td><td>Atelier CV et lettre de motivation</td><td>Structurer les candidatures des apprenants</td></tr>
<tr><td>Milieu de parcours</td><td>Simulation d''entretien</td><td>Préparer les apprenants aux entretiens d''embauche</td></tr>
<tr><td>Milieu de parcours</td><td>Intervention d''un partenaire insertion/PSH</td><td>Sensibilisation à l''insertion des publics spécifiques</td></tr>
<tr><td>Fin de parcours</td><td>Atelier LinkedIn et e-réputation</td><td>Développer la visibilité professionnelle</td></tr>
<tr><td>Fin de parcours</td><td>Diffusion d''offres de stage/emploi</td><td>Concrétiser l''insertion</td></tr>
<tr><td>Fin de parcours</td><td>Atelier orientation RNCP / poursuites d''études</td><td>Informer sur les suites de parcours possibles</td></tr>
</tbody></table>', null, 'global'),
('procedure_accompagnement_insertion', 'ateliers', 'Ateliers proposés', 6, 'content_block_list', null, 'insertion_workshop', 'global'),
('procedure_recueil_appreciations', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de recueil des appréciations des parties prenantes<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_recueil_appreciations', 'objectif', 'Objectif', 2, 'rich_text', '<p>Garantir la collecte, l''analyse et l''exploitation des retours de l''ensemble des parties prenantes : apprenants, formateurs, entreprises partenaires et financeurs.</p>', null, 'global'),
('procedure_recueil_appreciations', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Qualité : organisation et centralisation des retours.</li><li>Direction pédagogique : analyse et intégration des améliorations.</li><li>Formateurs : contribution au recueil (animation, transmission des questionnaires).</li></ul>', null, 'global'),
('procedure_recueil_appreciations', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Apprenants : questionnaires de satisfaction en fin de formation + enquêtes à froid.</li><li>Formateurs : questionnaires internes et réunions pédagogiques semestrielles.</li><li>Entreprises partenaires : questionnaires de satisfaction après l''accueil d''un stagiaire/apprenant.</li><li>Financeurs : bilans transmis annuellement et sollicitations de retours écrits.</li><li>Analyse : compilation des résultats dans un tableau de synthèse.</li><li>Amélioration : intégration des actions correctives dans le plan qualité.</li></ol>', null, 'global'),
('procedure_recueil_appreciations', 'archivage', 'Archivage', 5, 'rich_text', '<p>Tous les questionnaires, synthèses et comptes rendus sont archivés {{archiving_duration}}.</p>', null, 'global'),
('procedure_recueil_appreciations', 'questionnaires', 'Banques de questions par partie prenante', 6, 'content_block_list', null, 'satisfaction_question', 'global'),
('procedure_recueil_appreciations', 'tableau_synthese_annuelle', 'Tableau de synthèse annuelle', 7, 'rich_text', '<table><thead><tr><th>Partie prenante</th><th>Nombre de retours</th><th>Taux de satisfaction</th><th>Points positifs</th><th>Points à améliorer</th><th>Actions mises en place</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_reclamations', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure de gestion des réclamations<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_reclamations', 'objectif', 'Objectif', 2, 'rich_text', '<p>Garantir la réception, l''analyse et le traitement de toutes les réclamations émises par les parties prenantes (apprenants, formateurs, entreprises, financeurs, partenaires).</p>', null, 'global'),
('procedure_reclamations', 'responsables', 'Responsables', 3, 'rich_text', '<ul><li>Référente Qualité : centralisation, suivi et clôture des réclamations.</li><li>Direction pédagogique : décision sur les actions correctives.</li><li>Formateurs : remontée d''information si une réclamation concerne leur session.</li></ul>', null, 'global'),
('procedure_reclamations', 'processus', 'Processus', 4, 'rich_text', '<ol><li>Réception : via formulaire papier, email ({{complaints_email}}) ou en direct auprès d''un membre de l''équipe.</li><li>Enregistrement : inscription immédiate dans le tableau de suivi des réclamations.</li><li>Accusé de réception : envoyé instantanément par e-mail.</li><li>Analyse : identification des causes avec les acteurs concernés.</li><li>Traitement : mise en place d''une action corrective ou préventive.</li><li>Clôture : confirmation envoyée à l''auteur de la réclamation.</li><li>Amélioration continue : intégration du retour d''expérience dans le plan qualité.</li></ol>', null, 'global'),
('procedure_reclamations', 'archivage', 'Archivage', 5, 'rich_text', '<p>Toutes les réclamations et leurs traitements sont conservés pendant {{archiving_duration}}.</p>', null, 'global'),
('procedure_reclamations', 'formulaire_reclamation', 'Formulaire de réclamation', 6, 'checklist', 'Nom / Prénom
Qualité (apprenant, formateur, entreprise, financeur, partenaire)
Formation concernée
Date
Objet de la réclamation
Détail de la réclamation
Proposition éventuelle de solution (facultatif)
J''accepte que mes données soient utilisées uniquement pour le traitement de ma réclamation (consentement RGPD)
Signature', null, 'global'),
('procedure_reclamations', 'tableau_suivi_reclamations', 'Tableau de suivi des réclamations', 7, 'rich_text', '<table><thead><tr><th>N°</th><th>Date</th><th>Auteur</th><th>Qualité</th><th>Objet</th><th>Action corrective</th><th>Responsable</th><th>Statut</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null, 'global'),
('procedure_reclamations', 'exemple_traite', 'Exemple de réclamation traitée (illustratif)', 8, 'content_block_list', null, 'complaint_resolution_example', 'global'),
('procedure_amelioration_continue', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Procédure d''amélioration continue<br/>Version : {{procedure_version}}</p>', null, 'global'),
('procedure_amelioration_continue', 'objectif', 'Objectif', 2, 'rich_text', '<p>Mettre en place un système d''amélioration continue pour garantir la qualité et la conformité des prestations de formation.</p>', null, 'global'),
('procedure_amelioration_continue', 'processus', 'Processus', 3, 'rich_text', '<ol><li>Collecte des données : questionnaires de satisfaction, réclamations, résultats pédagogiques (taux de réussite, insertion).</li><li>Analyse : compilation dans un tableau de bord qualité, identification des écarts et tendances.</li><li>Actions correctives et préventives : élaboration d''un plan d''action, attribution des responsabilités.</li><li>Suivi : vérification en réunion qualité semestrielle, intégration des résultats dans le rapport annuel.</li></ol>', null, 'global'),
('procedure_amelioration_continue', 'tableau_bord_qualite', 'Tableau de bord qualité', 4, 'rich_text', '<table><thead><tr><th>Indicateur</th><th>Objectif</th><th>Résultat</th><th>Analyse</th><th>Action corrective</th></tr></thead><tbody>
<tr><td>Satisfaction apprenants</td><td>≥ {{satisfaction_rate_target}}</td><td>{{computed_learner_satisfaction}}</td><td></td><td></td></tr>
<tr><td>Satisfaction formateurs</td><td>≥ {{trainer_satisfaction_rate_target}}</td><td>{{computed_trainer_satisfaction}}</td><td></td><td></td></tr>
<tr><td>Satisfaction entreprises</td><td>≥ {{partner_satisfaction_rate_target}}</td><td>{{computed_partner_satisfaction}}</td><td></td><td></td></tr>
<tr><td>Réclamations traitées</td><td>100 %</td><td>{{computed_complaints_resolved_ratio}}</td><td></td><td></td></tr>
<tr><td>Taux de réussite</td><td>≥ {{success_rate_target}}</td><td>{{computed_success_rate}}</td><td></td><td></td></tr>
<tr><td>Taux d''insertion (6 mois)</td><td>≥ {{insertion_rate_target_6months}}</td><td>{{computed_insertion_rate}}</td><td></td><td></td></tr>
</tbody></table>', null, 'global'),
('procedure_amelioration_continue', 'kpis', 'Indicateurs suivis par défaut', 5, 'content_block_list', null, 'quality_kpi_default', 'global'),
('procedure_anti_abandon', 'objectif_perimetre', 'Objectif et périmètre', 1, 'rich_text', '<p><strong>Objectif.</strong> Réduire au maximum les absences et abandons par un suivi pédagogique structuré, des relances systématiques et des adaptations si besoin (PSH).</p><p><strong>Périmètre.</strong> Toutes les actions de formation {{company_name}} (présentiel, distanciel, mixte).</p>', null, 'global'),
('procedure_anti_abandon', 'avant_pendant_formation', 'Avant et pendant la formation', 2, 'rich_text', '<p><strong>Avant la formation :</strong></p>
<ul><li>Analyse de besoin et positionnement.</li><li>Envoi convocation + rappel J-3/J-1.</li><li>Information accessibilité/PSH.</li></ul>
<p><strong>Pendant la formation :</strong></p>
<ul><li>Émargement numérique.</li><li>Suivi pédagogique (livret de suivi).</li><li>Relances si absence non prévue.</li></ul>', null, 'global'),
('procedure_anti_abandon', 'workflow_relances', 'Workflow de relances', 3, 'rich_text', '<table><thead><tr><th>Délai</th><th>Action</th></tr></thead><tbody><tr><td>{{absence_relance_delay_1}}</td><td>SMS + email (rappel lien de classe/lieu, demande de confirmation)</td></tr><tr><td>{{absence_relance_delay_2}}</td><td>Appel téléphonique + message vocal si besoin</td></tr><tr><td>{{absence_relance_delay_3}}</td><td>Email récapitulatif + nouvelle proposition d''aménagement / rattrapage</td></tr></tbody></table><p>Chaque relance est tracée (date, canal, motif, justificatif).</p>', null, 'global'),
('procedure_anti_abandon', 'prevention_psh', 'Prévention de l''abandon et public PSH', 4, 'rich_text', '<p><strong>Prévention :</strong></p>
<ul><li>Point intermédiaire à mi-parcours.</li><li>Aménagements (rythme, créneaux, tutorat).</li><li>Information tuteur/entreprise si alternance.</li></ul>
<p><strong>Public PSH :</strong></p>
<ul><li>Entretien individuel de besoins.</li><li>Aménagements (supports, temps, accessibilité outils).</li><li>Suivi renforcé via {{disability_referent_name}}.</li></ul>', null, 'global'),
('procedure_anti_abandon', 'tracabilite_preuves', 'Traçabilité et preuves', 5, 'checklist', 'Émargements signés
Journal des relances
Échanges livret de suivi
Justificatifs d''absence & comptes-rendus d''entretien', null, 'global'),
('procedure_anti_abandon', 'indicateurs_suivi', 'Indicateurs de suivi', 6, 'rich_text', '<p>Taux de présence global, taux d''absences justifiées, délai moyen de 1ʳᵉ relance, taux d''abandon par formation — à suivre dans un tableau de bord Assiduité dédié.</p>', null, 'global'),
('charte_engagement_assiduite', 'engagement_apprenant', 'Engagement de l''apprenant', 1, 'rich_text', '<ul><li>Participer assidûment et signer l''émargement numérique.</li><li>Prévenir au plus tôt en cas d''empêchement (justificatif si besoin).</li><li>Consulter le livret de suivi et répondre aux relances.</li></ul>', null, 'global'),
('charte_engagement_assiduite', 'engagement_organisme', 'Engagement de l''organisme', 2, 'rich_text', '<ul><li>Informer clairement (convocation, rappels), accompagner et adapter si besoin (PSH).</li><li>Relancer systématiquement en cas d''absence ({{absence_relance_delay_1}}, {{absence_relance_delay_2}}, {{absence_relance_delay_3}}).</li><li>Suivre les indicateurs d''assiduité et proposer des solutions de rattrapage.</li></ul>', null, 'global'),
('charte_engagement_assiduite', 'protection_donnees', 'Protection des données', 3, 'rich_text', '<p>Les données collectées sont strictement utilisées pour la gestion de la formation et de l''assiduité. Contact protection des données : {{dpo_contact_email}}. Droits d''accès, rectification, opposition : voir la politique de confidentialité.</p>', null, 'global'),
('charte_engagement_assiduite', 'signatures', 'Signatures', 4, 'rich_text', '<div style="display:flex; gap:24pt; margin-top:12pt;">
<div style="flex:1;"><p>Apprenant(e)<br/>Nom, prénom : ……………………</p><div class="signature-line">Signature — Date : ……………………</div></div>
<div style="flex:1;"><p>{{company_name}}<br/>Représenté(e) par {{manager_name}}</p><div class="signature-line">Signature — Date : ……………………</div></div>
</div>', null, 'global');

insert into content_blocks (category_id, type, code, text, is_active) values
(null, 'job_description', 'JOB_PEDAGOGICAL_REFERENT', 'Référent·e Pédagogique — Finalité : Piloter la stratégie pédagogique, garantir la qualité des contenus et coordonner les actions de formation. Missions principales : définir et décliner la stratégie pédagogique, veiller à son application cohérente dans les formations ; concevoir, valider et actualiser les contenus, supports, outils pédagogiques (présentiels ou digitaux) ; organiser les programmes, plannings, réunions pédagogiques et accompagner les formateurs (ingénierie de formation, animation, méthodologie) ; mettre en place et suivre les dispositifs d''évaluation (stagiaires/formateurs), capitaliser les bonnes pratiques ; animer une communauté de pratiques entre formateurs si existante. Compétences : ingénierie de formation, conception pédagogique, évaluation ; maîtrise des outils numériques, plateformes LMS/LCMS ; capacité à coordonner, animer des équipes, rigueur, esprit de synthèse et d''organisation.', true),
(null, 'job_description', 'JOB_ADMINISTRATIVE_REFERENT', 'Référent·e Administratif·ve — Finalité : Assurer la gestion administrative, logistique et réglementaire des actions de formation. Missions principales : gérer les inscriptions, convocations, contrats, conventions et bases de données stagiaires/formateurs ; organiser la logistique (salles, planning, émargement), suivre les financements (OPCO, taxes, bilans pédagogiques et financiers) ; assurer le suivi juridique, fiscal et réglementaire (déclarations, contributions, veille) ; rendre compte de l''avancement des actions de formation. Compétences : organisation administrative, rigueur, maîtrise des outils bureautiques et logiciels métiers formation ; connaissance du cadre légal de la formation professionnelle, procédures OPCO, gestion de la taxe d''apprentissage.', true),
(null, 'job_description', 'JOB_DISABILITY_REFERENT', 'Référent·e Handicap — Finalité : Garantir l''inclusion des personnes en situation de handicap dans les parcours de formation. Missions principales : accueil et accompagnement personnalisé des apprenants handicapés, identification des besoins et parcours sécurisés ; coordination avec les formateurs, structures spécialisées, employeurs, dispositifs d''orientation/insertion ; sensibilisation/formation des équipes sur les enjeux handicap. Compétences : empathie, écoute active, sens de la communication ; connaissance des dispositifs handicap, adaptation pédagogique et coordination intersectorielle.', true),
(null, 'job_description', 'JOB_DIRECTOR_COMBINED', 'Direction / Gestion / Commercial / Technique (fonction combinée ou indépendante) — Finalité : Piloter la stratégie globale de l''organisme, assurer sa pérennité, sa visibilité et son fonctionnement technique. Missions principales : définir la stratégie globale (commerciale, communication, gestion), suivre la rentabilité et le budget ; prospecter, promouvoir l''offre (marketing digital, sites internet, réseaux sociaux) ; gérer la relation financeur / client, négocier les contrats de prestation / travail ; superviser les outils techniques (site web, plateforme e-learning, matériel). Compétences : management de projet, marketing digital, gestion administrative, maîtrise des outils informatiques et CMS/LMS.', true),
(null, 'required_skill', 'SKILL_MARKETING_DIGITAL', 'Marketing digital — Expertise en stratégie digitale, maîtrise des outils publicitaires (Meta Ads, Google Ads), expérience en gestion de campagnes.', true),
(null, 'required_skill', 'SKILL_WEB_WORDPRESS', 'Web / WordPress — Maîtrise de WordPress/Elementor, notions de HTML/CSS, gestion hébergement/domaine.', true),
(null, 'required_skill', 'SKILL_SEO_SEA', 'SEO / SEA — Référencement naturel, audit SEO, Google Analytics.', true),
(null, 'required_skill', 'SKILL_COMMUNITY_MANAGEMENT', 'Community Management — Stratégie réseaux sociaux, animation de communauté, création de contenu.', true),
(null, 'required_skill', 'SKILL_COMMUNICATION_DIGITALE', 'Communication digitale — Stratégie multicanale, storytelling, communication de crise.', true),
(null, 'required_skill', 'SKILL_MONTAGE_VIDEO', 'Montage vidéo — Logiciels Adobe Premiere/After Effects, storytelling vidéo.', true),
(null, 'required_skill', 'SKILL_IA_OUTILS_USAGES', 'Outils IA — Outils IA (ChatGPT, Midjourney, IA marketing), pédagogie de l''innovation.', true),
(null, 'required_skill', 'SKILL_BUREAUTIQUE', 'Bureautique — Pack Office, Google Workspace, gestion collaborative.', true),
(null, 'required_skill', 'SKILL_MANAGEMENT', 'Management — Conduite d''équipe, gestion de projet, entretiens professionnels.', true),
(null, 'required_skill', 'SKILL_LANGUE_ANGLAIS', 'Langue anglaise — Maîtrise pédagogique, certification linguistique (TOEIC, CLES, Cambridge) — niveaux A1-C2.', true),
(null, 'required_skill', 'SKILL_LANGUE_FRANCAIS', 'Langue française (FLE) — Didactique du FLE, certification universitaire — niveaux A1-C2.', true),
(null, 'training_axis', 'AXIS_DIGITAL_TOOLS', 'Digital & outils pédagogiques — maîtrise avancée des plateformes LMS/outils collaboratifs (ex. Moodle, Teams, Digiforma).', true),
(null, 'training_axis', 'AXIS_METIER_EVOLUTIONS', 'Évolutions métier — perfectionnement en IA appliquée, SEO avancé, communication digitale.', true),
(null, 'training_axis', 'AXIS_LANGUES_INTERCULTUREL', 'Langues & interculturel — renforcement en anglais professionnel (niveaux C1/C2).', true),
(null, 'training_axis', 'AXIS_MANAGEMENT_RH', 'Management & RH — formation à la conduite des entretiens annuels et à l''accompagnement des PSH.', true),
(null, 'watch_source_legal', 'WATCH_SOURCE_LEGAL_NATIONAL', 'Sources nationales : Ministère du Travail (travail-emploi.gouv.fr), France Compétences (francecompetences.fr), Centre Inffo (centre-inffo.fr).', true),
(null, 'watch_example', 'WATCH_EXAMPLE_CPF', 'Réforme CPF : reste à charge obligatoire → impact : modification CGV et information sur site web.', true),
(null, 'watch_example', 'WATCH_EXAMPLE_ARCHIVING', 'Nouvelle obligation d''archivage numérique des documents formation → impact : conserver tous les justificatifs 5 ans.', true),
(null, 'watch_example', 'WATCH_EXAMPLE_OPCO_FUNDING', 'Nouveaux financements OPCO pour TPE → impact : opportunité de financement à communiquer aux clients.', true),
(null, 'watch_example', 'WATCH_EXAMPLE_ACCESSIBILITY', 'Actualisation des critères d''accessibilité (MDPH / Handicap.fr) → impact : réviser livret d''accueil et supports e-learning pour PSH.', true),
(null, 'watch_source_metiers', 'WATCH_SOURCE_METIERS_NATIONAL', 'Sources nationales : France Compétences (publications officielles), revues spécialisées nationales (Blog du Modérateur, Harvard Business Review, Stratégies).', true),
(null, 'program_adaptation_example', 'PROGRAM_ADAPTATION_EXAMPLE_CM_TIKTOK', 'Formation Community Management — ajout d''un « Module TikTok et contenus vidéo courts B2B » (étude de cas d''entreprises, atelier calendrier éditorial TikTok, mesure de performance vidéos courtes), suite à une remontée de veille métiers sur la forte demande de compétences Community Management/TikTok en entreprise.', true),
(null, 'watch_source_pedagogical', 'WATCH_SOURCE_PEDAGOGICAL_TOOLS', 'Salons/conférences (Learning Technologies, EdTech World), revues spécialisées (EducPros, Blog du Modérateur, EdTech France), réseaux LinkedIn (« EdTech France », « Pédagogie digitale »), plateformes EdTech (LMS type Moodle/Digiforma, Google Workspace, Canva, outils IA génériques).', true),
(null, 'pedagogical_innovation', 'INNOVATION_MICROLEARNING', 'Micro-learning — capsules vidéo courtes pour favoriser la mémorisation et l''engagement.', true),
(null, 'pedagogical_innovation', 'INNOVATION_GAMIFICATION', 'Gamification — badges et quiz interactifs pour augmenter la motivation des apprenants.', true),
(null, 'pedagogical_innovation', 'INNOVATION_IA_PERSONNALISATION', 'IA générative pour la personnalisation pédagogique — adapter les supports au niveau de chaque apprenant.', true),
(null, 'pedagogical_innovation', 'INNOVATION_BLENDED_LEARNING', 'Blended learning — mix présentiel/distanciel pour optimiser la flexibilité.', true),
(null, 'program_adaptation_example', 'PROGRAM_ADAPTATION_EXAMPLE_CM_HYBRID', 'Formation Community Management — ajout d''un module hybride (outils collaboratifs, classe virtuelle, quiz gamifiés via LMS), suite à une veille pédagogique sur les formats hybrides.', true),
(null, 'partner_disability', 'PARTNER_HANDICAP_NATIONAL', 'Agefiph (appui aux entreprises et organismes de formation, agefiph.fr), FIPHFP (fonds pour l''insertion des PSH dans la fonction publique, fiphfp.fr), Handicap.fr (portail national d''information, handicap.fr), Ressource Handicap Formation (accompagnement des organismes dans l''adaptation de leurs parcours).', true),
(null, 'commitment_text', 'CHARTE_ACCESSIBILITE_DEFAUT', '{{company_name}} s''engage à : 1. Accueillir toute personne sans discrimination. 2. Garantir l''accessibilité physique et numérique des formations. 3. Adapter les méthodes pédagogiques selon les besoins (supports adaptés, outils numériques inclusifs, temps supplémentaire). 4. Former les équipes à la prise en compte des situations de handicap. 5. Collaborer avec un réseau local de partenaires spécialisés en {{region}}. 6. Évaluer régulièrement l''efficacité des aménagements mis en place. Charte validée par la Direction et communiquée à chaque nouvel apprenant.', true),
(null, 'commitment_text', 'CHARTE_QUALITE_SOUS_TRAITANTS', 'Charte qualité pour les intervenants sous-traitants de {{company_name}}. Le sous-traitant s''engage à : 1. Respecter le référentiel Qualiopi et les processus internes de {{company_name}}. 2. Dispenser des formations conformes aux objectifs pédagogiques validés. 3. Garantir la confidentialité des données des apprenants. 4. Respecter la législation sociale et fiscale (portage ou statut indépendant). 5. Transmettre ses CV, diplômes, certificats à jour. 6. Participer au processus d''évaluation qualité (questionnaires, bilans).', true),
(null, 'legal_clause', 'CONTRACT_SOUS_TRAITANCE', 'CONTRAT DE SOUS-TRAITANCE (trame) — Entre {{company_name}}, organisme de formation certifié Qualiopi, dont le siège est à {{organization_city}}, représenté par {{director_name}}, et le sous-traitant (formateur indépendant, SIRET à préciser). Article 1 – Objet : le présent contrat définit les conditions dans lesquelles le sous-traitant dispense une action de formation pour le compte de {{company_name}}. Article 2 – Obligations du sous-traitant : assurer les formations conformément aux objectifs définis par {{company_name}} ; respecter le référentiel qualité Qualiopi et la charte qualité jointe ; fournir les justificatifs demandés (CV, diplômes, assurances). Article 3 – Obligations de {{company_name}} : mettre à disposition les informations pédagogiques nécessaires ; suivre et évaluer la prestation ; rémunérer le sous-traitant selon les conditions définies. Article 4 – Durée : à préciser pour chaque mission. Article 5 – Litiges : réglés à l''amiable ou, à défaut, par le {{jurisdiction}}.', true),
(null, 'legal_clause', 'CONTRACT_CONVENTION_PARTENARIAT', 'CONVENTION DE PARTENARIAT (trame) — Entre {{company_name}}, organisme de formation, représenté par {{director_name}}, et l''entreprise partenaire. Article 1 – Objet : cette convention définit les modalités de collaboration entre {{company_name}} et l''entreprise partenaire pour l''accueil d''apprenants en formation. Article 2 – Engagements de l''entreprise : accueillir l''apprenant selon les dates convenues ; désigner un tuteur référent ; fournir des missions en cohérence avec les objectifs pédagogiques. Article 3 – Engagements de {{company_name}} : assurer le suivi pédagogique de l''apprenant ; organiser des points réguliers avec le tuteur ; intervenir en cas de difficulté. Article 4 – Durée : à préciser pour chaque convention, fait à {{organization_city}}.', true),
(null, 'insertion_workshop', 'WORKSHOP_CV_LETTRE_MOTIVATION', 'Atelier CV et lettre de motivation — révision des structures de CV adaptées au secteur, rédaction ciblée de lettres de motivation.', true),
(null, 'insertion_workshop', 'WORKSHOP_SIMULATION_ENTRETIEN', 'Simulation d''entretien — mise en situation réelle (questions recruteur, pitch des apprenants), feedback personnalisé.', true),
(null, 'insertion_workshop', 'WORKSHOP_LINKEDIN_EREPUTATION', 'Atelier LinkedIn et e-réputation — développement de la visibilité professionnelle en ligne.', true),
(null, 'insertion_workshop', 'WORKSHOP_ORIENTATION_RNCP', 'Atelier orientation RNCP / poursuites d''études — information sur équivalences, passerelles, poursuites d''études.', true),
(null, 'satisfaction_question', 'QUEST_LEARNER_01', 'La formation a-t-elle répondu à vos attentes ? (Oui/Partiellement/Non)', true),
(null, 'satisfaction_question', 'QUEST_LEARNER_02', 'Les objectifs pédagogiques étaient-ils clairs ?', true),
(null, 'satisfaction_question', 'QUEST_LEARNER_03', 'Le formateur a-t-il su s''adapter à votre niveau ?', true),
(null, 'satisfaction_question', 'QUEST_LEARNER_04', 'Quels points amélioreriez-vous ?', true),
(null, 'satisfaction_question', 'QUEST_TRAINER_01', 'Les moyens pédagogiques mis à disposition étaient-ils suffisants ?', true),
(null, 'satisfaction_question', 'QUEST_TRAINER_02', 'Le suivi administratif est-il satisfaisant ?', true),
(null, 'satisfaction_question', 'QUEST_TRAINER_03', 'Quels ajustements recommandez-vous pour améliorer la formation ?', true),
(null, 'satisfaction_question', 'QUEST_PARTNER_COMPANY_01', 'Le stagiaire/apprenant a-t-il été bien préparé à ses missions ?', true),
(null, 'satisfaction_question', 'QUEST_PARTNER_COMPANY_02', 'La communication avec {{company_name}} a-t-elle été fluide ?', true),
(null, 'satisfaction_question', 'QUEST_PARTNER_COMPANY_03', 'Seriez-vous prêt(e) à accueillir de nouveau un apprenant de {{company_name}} ?', true),
(null, 'satisfaction_question', 'QUEST_FUNDER_01', 'Le reporting fourni par {{company_name}} répond-il à vos attentes ?', true),
(null, 'satisfaction_question', 'QUEST_FUNDER_02', 'La qualité pédagogique observée correspond-elle aux critères attendus ?', true),
(null, 'satisfaction_question', 'QUEST_FUNDER_03', 'Recommanderiez-vous {{company_name}} comme organisme partenaire ?', true),
(null, 'complaint_resolution_example', 'COMPLAINT_EXAMPLE_TECH_ISSUE', 'Contexte : un apprenant a signalé par mail ne pas pouvoir se connecter à la plateforme e-learning. Analyse : vérification technique — bug temporaire lié à une mise à jour serveur ; plusieurs apprenants concernés pendant 24h. Action corrective : intervention de l''équipe technique (réglage du serveur), envoi d''un tutoriel PDF et vidéo, mise en place d''une hotline dédiée de support technique. Clôture : réclamation résolue sous 48h, confirmation envoyée à l''apprenant avec excuses et explication.', true),
(null, 'quality_kpi_default', 'KPI_SATISFACTION_LEARNERS', 'Satisfaction apprenants — objectif par défaut lié à la cible « Objectif satisfaction apprenants » (Mes informations qualité).', true),
(null, 'quality_kpi_default', 'KPI_SATISFACTION_TRAINERS', 'Satisfaction formateurs — objectif par défaut lié à la cible « Objectif satisfaction formateurs ».', true),
(null, 'quality_kpi_default', 'KPI_SATISFACTION_PARTNER_COMPANIES', 'Satisfaction entreprises partenaires — objectif par défaut lié à la cible « Objectif satisfaction entreprises ».', true),
(null, 'quality_kpi_default', 'KPI_COMPLAINTS_RESOLVED', 'Réclamations traitées — objectif fixe 100 %.', true),
(null, 'quality_kpi_default', 'KPI_SUCCESS_RATE', 'Taux de réussite — objectif par défaut lié à la cible « Objectif taux de réussite ».', true),
(null, 'quality_kpi_default', 'KPI_INSERTION_RATE_6M', 'Taux d''insertion à 6 mois — objectif par défaut lié à la cible « Objectif taux d''insertion à 6 mois ».', true);
