-- Migration 0013 : documents liés à la session (étapes "avant / pendant /
-- après formation" du workflow) — devis, convention, contrat, convocation,
-- feuille d'émargement, attestation de fin de formation.
-- Rédaction originale (pas de contenu source Pivot Formation pour ceux-ci,
-- contrairement aux 15 documents transverses de la migration 0009) — cf.
-- claude/journal-avancement.md "Reste à faire" point 3.
-- Convention (art. L6353-1 et L6353-2 du Code du travail) et Contrat
-- (art. L6353-3 à L6353-7 du Code du travail, rétractation de 10 jours,
-- acompte plafonné à 30 %) à faire valider par Nora avant usage réel.

-- =========================================================
-- 1. Clauses juridiques (banque de contenu, réutilisables et modifiables
--    depuis le futur back-office sans toucher au code) — types dédiés pour
--    ne pas se mélanger avec le type 'legal_clause' déjà utilisé par les
--    trames de sous-traitance / partenariat (migration 0009).
-- =========================================================

insert into content_blocks (category_id, type, code, text, is_active) values
(null, 'legal_clause_convention', 'CONV_CL_01_OBJET', 'La présente convention est conclue en application des articles L6353-1 et L6353-2 du Code du travail. Elle a pour objet la réalisation d''une action de formation professionnelle entrant dans le champ d''application de l''article L6313-1 du Code du travail, organisée par {{company_name}} au bénéfice du personnel de l''entreprise ou de l''organisme cocontractant.', true),
(null, 'legal_clause_convention', 'CONV_CL_02_INTITULE_DUREE', 'Intitulé de la formation : {{training_name}}. Durée : {{training_duration}} heures. Dates prévisionnelles : du {{training_start_date}} au {{training_end_date}}. Modalité : {{training_modality}}. Lieu : {{training_location}}. Nombre de participants prévu : {{participant_count}}.', true),
(null, 'legal_clause_convention', 'CONV_CL_03_OBJECTIFS_PROGRAMME', 'Les objectifs pédagogiques et le programme détaillé de la formation figurent dans le document « Programme de formation » remis préalablement au cocontractant et annexé à la présente convention.', true),
(null, 'legal_clause_convention', 'CONV_CL_04_MOYENS', '{{company_name}} met en œuvre les moyens pédagogiques, techniques et d''encadrement décrits dans le programme de formation annexé, adaptés au format {{training_modality}} et au public visé.', true),
(null, 'legal_clause_convention', 'CONV_CL_05_EVALUATION_SANCTION', 'Les modalités d''évaluation des acquis sont précisées dans le programme de formation. À l''issue de l''action, {{company_name}} délivre une attestation de fin de formation mentionnant les résultats de l''évaluation des acquis, ainsi qu''une feuille d''émargement signée par demi-journée.', true),
(null, 'legal_clause_convention', 'CONV_CL_06_PRIX_REGLEMENT', 'Le prix de l''action de formation est fixé à {{price_amount_formatted}} ({{price_unit_label}}). Modalités de règlement : {{payment_terms}}. Toute somme versée fait l''objet d''une facture émise par {{company_name}}.', true),
(null, 'legal_clause_convention', 'CONV_CL_07_DEDIT_ANNULATION', 'En cas de résiliation à l''initiative de l''une des parties moins de dix jours ouvrés avant le début de l''action, et sauf cas de force majeure dûment reconnu, une indemnité correspondant aux frais déjà engagés par {{company_name}} pourra être due, dans la limite des dispositions applicables. En cas d''abandon en cours de formation par un participant, seules les prestations effectivement dispensées sont dues, sauf disposition contraire prévue par le financeur.', true),
(null, 'legal_clause_convention', 'CONV_CL_08_DIFFERENDS', 'Si un différend survient à l''occasion de l''interprétation ou de l''exécution de la présente convention, les parties s''efforcent de le résoudre à l''amiable. À défaut d''accord, le litige est porté devant le {{jurisdiction}}.', true),
(null, 'legal_clause_convention', 'CONV_CL_09_DONNEES_PERSONNELLES', 'Les données à caractère personnel des participants sont traitées par {{company_name}} conformément au Règlement Général sur la Protection des Données (RGPD), dans le seul cadre de l''exécution de la présente convention et de ses obligations Qualiopi. Contact : {{dpo_contact_email}}.', true),

(null, 'legal_clause_contrat', 'CONTRAT_CL_01_OBJET', 'Le présent contrat est conclu en application des articles L6353-3 à L6353-7 du Code du travail. Il a pour objet la réalisation, par {{company_name}}, d''une action de formation professionnelle au bénéfice de {{student_name}}, qui s''inscrit à titre individuel et à ses frais personnels.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_02_INTITULE_PROGRAMME', 'Intitulé de la formation : {{training_name}}. Durée : {{training_duration}} heures. Dates prévisionnelles : du {{training_start_date}} au {{training_end_date}}. Modalité : {{training_modality}}. Lieu : {{training_location}}. Le programme détaillé, les objectifs pédagogiques et les prérequis sont annexés au présent contrat.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_03_MOYENS_EVALUATION', '{{company_name}} met en œuvre les moyens pédagogiques, techniques et d''encadrement décrits dans le programme annexé. Les modalités d''évaluation des acquis et la nature de la sanction délivrée à l''issue de la formation (attestation de fin de formation) sont également précisées dans ce programme.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_04_PRIX', 'Le prix de la formation est fixé à {{price_amount_formatted}} ({{price_unit_label}}). {{payment_terms}}', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_05_RETRACTATION', 'Conformément à l''article L6353-5 du Code du travail, {{student_name}} dispose d''un délai de dix jours, à compter de la signature du présent contrat, pour se rétracter. Il en informe {{company_name}} par lettre recommandée avec accusé de réception. Aucune somme ne peut être exigée avant l''expiration de ce délai.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_06_ACOMPTE', 'À l''expiration du délai de rétractation, {{student_name}} s''acquitte, conformément à l''article L6353-6 du Code du travail, d''un acompte qui ne peut excéder 30 % du prix total de la formation ; le solde est réglé selon les modalités précisées à l''article « Prix ».', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_07_INEXECUTION', 'Si {{student_name}} abandonne la formation en cours d''exécution du contrat pour un motif autre que la force majeure dûment reconnue, le contrat est résilié. Conformément à l''article L6353-7 du Code du travail, seules sont dues à {{company_name}} les sommes correspondant aux prestations effectivement dispensées, évaluées au prorata temporis de leur valeur prévue au contrat, en sus, le cas échéant, d''une indemnité qui ne peut excéder 30 % du montant correspondant à la partie non exécutée du contrat.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_08_DIFFERENDS', 'En cas de différend né de l''interprétation ou de l''exécution du présent contrat, les parties s''efforcent de trouver une solution amiable. À défaut, le litige relève du {{jurisdiction}}.', true),
(null, 'legal_clause_contrat', 'CONTRAT_CL_09_DONNEES_PERSONNELLES', 'Les données à caractère personnel de {{student_name}} sont traitées par {{company_name}} conformément au RGPD, dans le seul cadre de l''exécution du présent contrat. Contact : {{dpo_contact_email}}.', true);

-- =========================================================
-- 2. Modèles de documents
-- =========================================================

insert into document_templates (id, label, category_scope, applicable_when, linked_indicator_numbers, folder_group, sort_order, is_active) values
('devis', 'Devis', 'all', '{}'::jsonb, ARRAY[1], '03_Avant_formation', 15, true),
('convention_formation', 'Convention de formation professionnelle (financement tiers)', 'all', '{}'::jsonb, ARRAY[1], '03_Avant_formation', 20, true),
('contrat_formation_particulier', 'Contrat de formation professionnelle (particulier)', 'all', '{}'::jsonb, ARRAY[1], '03_Avant_formation', 22, true),
('convocation', 'Convocation', 'all', '{}'::jsonb, ARRAY[9], '03_Avant_formation', 25, true),
('feuille_emargement', 'Feuille d''émargement', 'all', '{}'::jsonb, ARRAY[10], '04_Pendant_formation', 10, true),
('attestation_fin_formation', 'Attestation de fin de formation', 'all', '{}'::jsonb, ARRAY[11], '05_Apres_formation', 10, true);

-- =========================================================
-- 3. Sections
-- =========================================================

insert into document_template_sections (document_template_id, code, title, sort_order, content_type, html_template, source_content_block_type, content_block_scope) values

-- ---------- DEVIS ----------
('devis', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — {{address}}<br/>SIRET {{siret}} — {{phone}} — {{email}}</p><p><strong>DEVIS N° {{quote_reference}}</strong><br/>Date d''émission : {{generated_date}}<br/>Validité : 30 jours à compter de la date d''émission</p><p><strong>Destinataire :</strong><br/>{{student_name}}<br/>{{student_company}}</p>', null, 'global'),
('devis', 'prestation', 'Prestation proposée', 2, 'rich_text', '<table><tbody><tr><th>Formation</th><td>{{training_name}}</td></tr><tr><th>Durée</th><td>{{training_duration}} heures</td></tr><tr><th>Dates prévisionnelles</th><td>Du {{training_start_date}} au {{training_end_date}}</td></tr><tr><th>Modalité</th><td>{{training_modality}}</td></tr><tr><th>Lieu</th><td>{{training_location}}</td></tr><tr><th>Nombre de participants</th><td>{{participant_count}}</td></tr></tbody></table>', null, 'global'),
('devis', 'tarif', 'Tarif', 3, 'rich_text', '<table><tbody><tr><th>{{price_unit_label}}</th><td>{{price_amount_formatted}}</td></tr></tbody></table><p>Mode de financement envisagé : {{funding_type_label}} {{funding_details}}</p>', null, 'global'),
('devis', 'modalites_reglement', 'Modalités de règlement', 4, 'rich_text', '<p>{{payment_terms}}</p>', null, 'global'),
('devis', 'conditions', 'Conditions', 5, 'rich_text', '<p>Ce devis constitue une proposition commerciale et ne vaut pas engagement contractuel définitif. Il sera formalisé, selon le mode de financement retenu, par une convention de formation professionnelle ou un contrat de formation professionnelle, conformément aux articles L6353-1 et suivants du Code du travail. Les conditions générales de vente de {{company_name}} sont disponibles sur demande.</p>', null, 'global'),
('devis', 'acceptation', 'Bon pour accord', 6, 'rich_text', '<table style="width:100%; margin-top:8pt;"><tbody><tr><td style="width:50%; vertical-align:top;">Pour {{company_name}}<br/>{{director_name}}<br/><br/>Date et signature :<br/><br/><br/></td><td style="width:50%; vertical-align:top;">Pour le client<br/>{{student_name}} — {{student_company}}<br/><br/>Date et signature (précédée de la mention manuscrite « Bon pour accord ») :<br/><br/><br/></td></tr></tbody></table>', null, 'global'),

-- ---------- CONVENTION DE FORMATION (tiers financeur) ----------
('convention_formation', 'header', 'Parties', 1, 'rich_text', '<p><strong>Entre les soussignés :</strong></p><p><strong>L''organisme de formation :</strong> {{company_name}} ({{commercial_name}}), SIRET {{siret}}, {{address}}, représenté par {{director_name}}, ci-après « l''organisme »,</p><p><strong>Et le cocontractant :</strong> {{student_company}}, représenté par ……………………………, ci-après « le cocontractant »,</p><p>Il est convenu ce qui suit — Référence : {{convention_reference}} — Fait à {{organization_city}}, le {{generated_date}}.</p>', null, 'global'),
('convention_formation', 'clauses', 'Articles', 2, 'content_block_list', null, 'legal_clause_convention', 'global'),
('convention_formation', 'annexes', 'Annexes', 3, 'rich_text', '<p>Sont annexés à la présente convention et en font partie intégrante : le programme de formation détaillé, le devis {{quote_reference}}, le règlement intérieur de {{company_name}}.</p>', null, 'global'),
('convention_formation', 'signatures', 'Signatures', 4, 'rich_text', '<table style="width:100%; margin-top:8pt;"><tbody><tr><td style="width:50%; vertical-align:top;">Pour l''organisme, {{company_name}}<br/>{{director_name}}<br/><br/>Date et signature :<br/><br/><br/></td><td style="width:50%; vertical-align:top;">Pour le cocontractant, {{student_company}}<br/><br/>Date et signature (précédée de la mention manuscrite « Lu et approuvé, bon pour accord ») :<br/><br/><br/></td></tr></tbody></table>', null, 'global'),

-- ---------- CONTRAT DE FORMATION (particulier autofinancé) ----------
('contrat_formation_particulier', 'header', 'Parties', 1, 'rich_text', '<p><strong>Entre les soussignés :</strong></p><p><strong>L''organisme de formation :</strong> {{company_name}} ({{commercial_name}}), SIRET {{siret}}, {{address}}, représenté par {{director_name}}, ci-après « l''organisme »,</p><p><strong>Et le stagiaire :</strong> {{student_name}}, ci-après « le stagiaire »,</p><p>Il est convenu ce qui suit — Fait à {{organization_city}}, le {{generated_date}}.</p>', null, 'global'),
('contrat_formation_particulier', 'clauses', 'Articles', 2, 'content_block_list', null, 'legal_clause_contrat', 'global'),
('contrat_formation_particulier', 'annexes', 'Annexes', 3, 'rich_text', '<p>Sont annexés au présent contrat et en font partie intégrante : le programme de formation détaillé et le règlement intérieur de {{company_name}}.</p>', null, 'global'),
('contrat_formation_particulier', 'signatures', 'Signatures', 4, 'rich_text', '<table style="width:100%; margin-top:8pt;"><tbody><tr><td style="width:50%; vertical-align:top;">Pour l''organisme, {{company_name}}<br/>{{director_name}}<br/><br/>Date et signature :<br/><br/><br/></td><td style="width:50%; vertical-align:top;">Le stagiaire, {{student_name}}<br/><br/>Date et signature (précédée de la mention manuscrite « Lu et approuvé, bon pour accord ») :<br/><br/><br/></td></tr></tbody></table>', null, 'global'),

-- ---------- CONVOCATION ----------
('convocation', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — {{address}}<br/>{{phone}} — {{email}}</p><p>{{organization_city}}, le {{generated_date}}</p><p><strong>Destinataire :</strong><br/>{{student_name}}<br/>{{student_company}}</p>', null, 'global'),
('convocation', 'objet', 'Objet', 2, 'rich_text', '<p>Nous avons le plaisir de vous convoquer à la formation <strong>« {{training_name}} »</strong>, dispensée par {{company_name}}.</p><table><tbody><tr><th>Dates</th><td>Du {{training_start_date}} au {{training_end_date}}</td></tr><tr><th>Durée</th><td>{{training_duration}} heures</td></tr><tr><th>Modalité</th><td>{{training_modality}}</td></tr><tr><th>Lieu</th><td>{{training_location}}</td></tr><tr><th>Formateur·rice</th><td>{{trainer_name}}</td></tr></tbody></table>', null, 'global'),
('convocation', 'infos_pratiques', 'Informations pratiques', 3, 'checklist', 'Se munir d''une pièce d''identité en cours de validité
Prévoir de quoi prendre des notes (le support de formation est fourni par ailleurs)
Pour une formation à distance : disposer d''une connexion internet stable et d''un accès à {{technical_provider_name}}
Prévenir {{administrative_referent_name}} au plus tôt en cas d''empêchement', null, 'global'),
('convocation', 'contact', 'Contacts', 4, 'rich_text', '<p>Pour toute question sur le contenu de la formation, vous pouvez contacter {{pedagogical_referent_name}} ({{pedagogical_referent_email}} / {{pedagogical_referent_phone}}).</p><p>Si vous êtes en situation de handicap et souhaitez signaler un besoin d''aménagement, contactez {{disability_referent_name}} ({{disability_referent_email}}).</p>', null, 'global'),
('convocation', 'signature', 'Signature', 5, 'signature_block', null, null, 'global'),

-- ---------- FEUILLE D'ÉMARGEMENT ----------
('feuille_emargement', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — {{address}}</p><p><strong>FEUILLE D''ÉMARGEMENT</strong></p><table><tbody><tr><th>Formation</th><td>{{training_name}}</td></tr><tr><th>Dates</th><td>Du {{training_start_date}} au {{training_end_date}}</td></tr><tr><th>Lieu</th><td>{{training_location}}</td></tr><tr><th>Formateur·rice</th><td>{{trainer_name}}</td></tr></tbody></table><p class="empty">Une feuille est à compléter pour chaque demi-journée de formation (matin / après-midi) — dupliquer cette page autant que nécessaire, en indiquant la date et le créneau ci-dessous.</p><p>Date : …………………………… &nbsp; Créneau : ☐ Matin &nbsp; ☐ Après-midi</p>', null, 'global'),
('feuille_emargement', 'table_emargement', 'Émargement', 2, 'rich_text', '<table><thead><tr><th>N°</th><th>Nom et prénom</th><th>Signature</th></tr></thead><tbody><tr><td>1</td><td>{{student_name}}</td><td></td></tr><tr><td>2</td><td></td><td></td></tr><tr><td>3</td><td></td><td></td></tr><tr><td>4</td><td></td><td></td></tr><tr><td>5</td><td></td><td></td></tr><tr><td>6</td><td></td><td></td></tr><tr><td>7</td><td></td><td></td></tr><tr><td>8</td><td></td><td></td></tr></tbody></table><p style="margin-top:12pt;">Signature du formateur / de la formatrice : ……………………………</p>', null, 'global'),
('feuille_emargement', 'mentions', 'Mentions', 3, 'rich_text', '<p>La présente feuille d''émargement est signée par chaque participant à chaque demi-journée de formation. Elle constitue, avec les évaluations et l''attestation de fin de formation, un justificatif de la réalisation effective de l''action, conservé par {{company_name}} pendant {{archiving_duration}}.</p>', null, 'global'),

-- ---------- ATTESTATION DE FIN DE FORMATION ----------
('attestation_fin_formation', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — {{address}}<br/>SIRET {{siret}}</p><p style="text-align:center; font-weight:600; font-size:13pt; margin-top:16pt;">ATTESTATION DE FIN DE FORMATION</p><p style="text-align:center;">Délivrée en application de l''article L6353-1 du Code du travail.</p>', null, 'global'),
('attestation_fin_formation', 'identification', 'Identification', 2, 'rich_text', '<p>Je soussigné(e) {{director_name}}, représentant {{company_name}}, atteste que :</p><p><strong>{{student_name}}</strong><br/>{{student_company}}</p><p>a suivi l''action de formation intitulée <strong>« {{training_name}} »</strong>, du {{training_start_date}} au {{training_end_date}}, d''une durée de {{training_duration}} heures, dispensée en modalité {{training_modality}} à {{training_location}}.</p>', null, 'global'),
('attestation_fin_formation', 'resultats', 'Nature de l''action et résultats', 3, 'rich_text', '<p><strong>Nature de l''action :</strong> action de formation entrant dans le champ d''application de l''article L6313-1 du Code du travail.</p><p><strong>Objectifs :</strong> conformes au programme de formation remis en amont de l''action.</p><p><strong>Résultats de l''évaluation des acquis :</strong></p><ul><li>☐ Objectifs de la formation atteints</li><li>☐ Objectifs partiellement atteints</li><li>☐ Objectifs non atteints</li></ul><p>Assiduité constatée sur la base de la feuille d''émargement : …..…… heures sur {{training_duration}} heures.</p>', null, 'global'),
('attestation_fin_formation', 'mention_legale', 'Mention légale', 4, 'rich_text', '<p>Cette attestation est délivrée pour permettre au bénéficiaire de faire valoir son droit à la formation, notamment auprès de son employeur ou d''un organisme financeur. Elle est distincte du certificat de réalisation le cas échéant transmis au financeur.</p>', null, 'global'),
('attestation_fin_formation', 'signature', 'Signature', 5, 'signature_block', null, null, 'global');
