-- Migration 0014 : Livret d''accueil + Règlement intérieur.
-- Complète la Phase 4 (documents liés à la session/à l''organisme, cf.
-- claude/journal-avancement.md). Les deux sont cités comme preuves types de
-- l''indicateur 9 (« Le prestataire informe les publics bénéficiaires des
-- conditions de déroulement de la prestation ») dans le guide officiel.
-- ⚠️ Le règlement intérieur contient des clauses encadrées par les articles
-- R6352-1 à R6352-15 du Code du travail (hygiène/sécurité, discipline,
-- sanctions, procédure disciplinaire, harcèlement) — à faire valider par
-- Nora avant usage réel, comme la convention et le contrat (migration 0013).

insert into content_blocks (category_id, type, code, text, is_active) values
(null, 'legal_clause_reglement', 'RI_CL_01_OBJET_CHAMP', 'Le présent règlement intérieur est établi conformément aux articles R6352-1 et suivants du Code du travail. Il s''applique à toute personne participant à une action de formation dispensée par {{company_name}}, pour toute la durée de la formation suivie, quel que soit le lieu de son déroulement (locaux de {{company_name}}, locaux mis à disposition par un tiers, ou à distance).', true),
(null, 'legal_clause_reglement', 'RI_CL_02_HYGIENE_SECURITE', 'Chaque stagiaire doit veiller à sa sécurité et à celle des autres personnes présentes, et respecter les consignes générales et particulières de sécurité en vigueur sur le ou les lieux de formation, notamment les consignes d''incendie. En cas de formation en distanciel, le stagiaire s''engage à suivre la formation dans des conditions garantissant sa sécurité (installation électrique conforme, poste de travail adapté).', true),
(null, 'legal_clause_reglement', 'RI_CL_03_DISCIPLINE_GENERALE', 'Les stagiaires sont tenus de respecter les horaires de formation communiqués dans la convocation. Toute absence ou retard doit être signalé et justifié auprès de {{administrative_referent_name}} dans les meilleurs délais. La présence est attestée par la signature de la feuille d''émargement à chaque demi-journée. Il est demandé à chaque stagiaire d''adopter un comportement courtois envers les autres stagiaires et le formateur, et de respecter le matériel mis à disposition. L''introduction, la consommation ou la diffusion de boissons alcoolisées ou de substances illicites dans l''enceinte de la formation est interdite.', true),
(null, 'legal_clause_reglement', 'RI_CL_04_SANCTIONS', 'Tout manquement du stagiaire aux dispositions du présent règlement pourra faire l''objet d''une sanction. Constitue une sanction toute mesure, autre que les observations verbales, prise par {{company_name}} à la suite d''un agissement du stagiaire considéré comme fautif : avertissement écrit, blâme, exclusion temporaire, exclusion définitive de la formation. Selon la gravité des faits, {{company_name}} en informe, le cas échéant, l''employeur et/ou l''organisme financeur du stagiaire.', true),
(null, 'legal_clause_reglement', 'RI_CL_05_PROCEDURE_DISCIPLINAIRE', 'Aucune sanction ne peut être infligée sans que le stagiaire en cause ait été informé au préalable des griefs retenus contre lui. Lorsque {{company_name}} envisage une sanction pouvant entraîner l''exclusion, elle convoque le stagiaire par lettre recommandée ou remise en main propre contre décharge, en lui indiquant l''objet de la convocation, la date, l''heure et le lieu de l''entretien, et en lui précisant qu''il peut se faire assister par une personne de son choix. La sanction ne peut intervenir moins d''un jour franc ni plus de quinze jours après l''entretien, et fait l''objet d''une décision écrite et motivée, notifiée au stagiaire.', true),
(null, 'legal_clause_reglement', 'RI_CL_06_HARCELEMENT', 'Aucun stagiaire ne doit subir des faits de harcèlement moral ou sexuel, ni des agissements sexistes, tels que définis par le Code pénal et le Code du travail. Tout stagiaire s''estimant victime ou témoin de tels faits est invité à en informer sans délai {{quality_referent_name}} ou {{director_name}}, qui prendront les mesures appropriées, y compris disciplinaires, à l''encontre de leur auteur.', true),
(null, 'legal_clause_reglement', 'RI_CL_07_PUBLICATION', 'Le présent règlement intérieur est communiqué à chaque stagiaire avant son inscription définitive, avec le programme de formation, et affiché dans les locaux de formation lorsque celle-ci se déroule en présentiel. Il entre en vigueur à la date de signature de la convention ou du contrat de formation.', true);

insert into document_templates (id, label, category_scope, applicable_when, linked_indicator_numbers, folder_group, sort_order, is_active) values
('livret_accueil', 'Livret d''accueil du stagiaire', 'all', '{}'::jsonb, ARRAY[9], '03_Avant_formation', 27, true),
('reglement_interieur', 'Règlement intérieur', 'all', '{}'::jsonb, ARRAY[9], '03_Avant_formation', 28, true);

insert into document_template_sections (document_template_id, code, title, sort_order, content_type, html_template, source_content_block_type, content_block_scope) values

-- ---------- LIVRET D'ACCUEIL ----------
('livret_accueil', 'bienvenue', 'Bienvenue', 1, 'rich_text', '<p>Bienvenue chez <strong>{{company_name}}</strong>. Ce livret d''accueil a pour objectif de vous donner toutes les informations pratiques utiles au bon déroulement de votre formation <strong>« {{training_name}} »</strong>.</p>', null, 'global'),
('livret_accueil', 'presentation_organisme', 'Présentation de l''organisme', 2, 'rich_text', '<p>{{company_name}} ({{commercial_name}}) est un organisme de formation certifié Qualiopi, dirigé par {{director_name}}. {{sole_practitioner_note}}</p><ul><li>Adresse : {{address}}</li><li>Téléphone : {{phone}} — Email : {{email}}</li><li>Site internet : {{company_website}}</li></ul>', null, 'global'),
('livret_accueil', 'interlocuteurs', 'Vos interlocuteurs', 3, 'rich_text', '<ul><li>Référent pédagogique : {{pedagogical_referent_name}} — {{pedagogical_referent_email}} / {{pedagogical_referent_phone}}</li><li>Référent administratif : {{administrative_referent_name}} — {{administrative_referent_email}} / {{administrative_referent_phone}}</li><li>Formateur·rice de votre session : {{trainer_name}}</li></ul>', null, 'global'),
('livret_accueil', 'votre_formation', 'Votre formation', 4, 'rich_text', '<table><tbody><tr><th>Intitulé</th><td>{{training_name}}</td></tr><tr><th>Dates</th><td>Du {{training_start_date}} au {{training_end_date}}</td></tr><tr><th>Durée</th><td>{{training_duration}} heures</td></tr><tr><th>Modalité</th><td>{{training_modality}}</td></tr><tr><th>Lieu</th><td>{{training_location}}</td></tr></tbody></table><p>Le programme détaillé (objectifs, contenu, méthodes, modalités d''évaluation) vous a été remis séparément.</p>', null, 'global'),
('livret_accueil', 'organisation_pratique', 'Organisation pratique', 5, 'rich_text', '<p>Les horaires précis vous sont communiqués dans votre convocation. En cas d''empêchement, prévenez {{administrative_referent_name}} au plus tôt. Votre présence est attestée par la signature d''une feuille d''émargement à chaque demi-journée. Pour une formation à distance, un accès à {{technical_provider_name}} vous est communiqué avant le début de l''action.</p>', null, 'global'),
('livret_accueil', 'accessibilite', 'Accessibilité et situation de handicap', 6, 'rich_text', '<p>Si vous êtes en situation de handicap et avez besoin d''un aménagement (matériel, rythme, durée, accessibilité des locaux...), contactez notre référent handicap, {{disability_referent_name}} ({{disability_referent_email}} / {{disability_referent_phone}}), le plus tôt possible avant le début de la formation afin d''étudier ensemble les solutions adaptées.</p>', null, 'global'),
('livret_accueil', 'reclamations', 'Réclamations', 7, 'rich_text', '<p>Si vous rencontrez une difficulté pendant votre formation, vous pouvez la signaler à tout moment à {{pedagogical_referent_name}}. Pour toute réclamation formelle, écrivez à {{complaints_email}} — elle sera traitée selon notre procédure de traitement des réclamations, disponible sur demande.</p>', null, 'global'),
('livret_accueil', 'reglement', 'Règlement intérieur', 8, 'rich_text', '<p>Le règlement intérieur applicable pendant votre formation vous est remis en document séparé et vous a été communiqué avant votre inscription définitive.</p>', null, 'global'),

-- ---------- RÈGLEMENT INTÉRIEUR ----------
('reglement_interieur', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — {{address}}</p><p>Version {{procedure_version}}</p>', null, 'global'),
('reglement_interieur', 'articles', 'Articles', 2, 'content_block_list', null, 'legal_clause_reglement', 'global'),
('reglement_interieur', 'entree_vigueur', 'Entrée en vigueur', 3, 'rich_text', '<p>Fait à {{organization_city}}, le {{generated_date}}.<br/>{{director_name}}, pour {{company_name}}.</p>', null, 'global');
