-- Migration 0017 : premier lot de documents identifiés manquants après
-- analyse des 87 vrais documents d'audit de Nora (cf. Phase 5 du journal).
-- Priorité haute : les indicateurs 2 et 17 n'avaient jusqu'ici AUCUN document
-- généré. On ajoute aussi le formulaire de réclamation (le formulaire
-- lui-même, pas seulement la procédure), son accusé de réception, le
-- questionnaire de recueil des besoins et le questionnaire de satisfaction,
-- dont la structure réelle a été extraite des vrais formulaires de Nora.
--
-- Réutilisation délibérée de l'existant plutôt que de nouveaux content_block
-- types : la fiche moyens pédagogiques réutilise le type 'method' (déjà
-- alimenté par domaine, cf. migrations 0005/0011) via content_block_scope
-- 'training', et le questionnaire de besoins réutilise 'need_example' de la
-- même façon — aucune nouvelle banque de contenu à créer pour ce lot.

insert into document_templates (id, label, category_scope, applicable_when, linked_indicator_numbers, folder_group, sort_order, is_active) values
('questionnaire_besoins', 'Questionnaire de recueil des besoins', 'all', '{}'::jsonb, ARRAY[4], '03_Avant_formation', 12, true),
('fiche_moyens_pedagogiques', 'Fiche des moyens pédagogiques, techniques et humains', 'all', '{}'::jsonb, ARRAY[17], '06_Procedures', 15, true),
('resultats_indicateurs_qualite', 'Nos résultats — indicateurs de résultats', 'all', '{}'::jsonb, ARRAY[2], '08_Amelioration', 105, true),
('formulaire_reclamation', 'Formulaire de réclamation', 'all', '{}'::jsonb, ARRAY[31], '08_Amelioration', 115, true),
('accuse_reception_reclamation', 'Accusé de réception d''une réclamation', 'all', '{}'::jsonb, ARRAY[31], '08_Amelioration', 116, true),
('questionnaire_satisfaction', 'Questionnaire de satisfaction', 'all', '{}'::jsonb, ARRAY[30], '05_Apres_formation', 20, true);

insert into document_template_sections (document_template_id, code, title, sort_order, content_type, html_template, source_content_block_type, content_block_scope) values

-- ---------- QUESTIONNAIRE DE RECUEIL DES BESOINS (indicateur 4) ----------
('questionnaire_besoins', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — Questionnaire de recueil des besoins</p><p>Formation envisagée : <strong>{{training_name}}</strong></p><p>Nom et prénom du bénéficiaire : …………………………………… &nbsp; Entreprise (le cas échéant) : ……………………………………</p><p>Date : …………………………………</p>', null, 'global'),
('questionnaire_besoins', 'situation', 'Situation actuelle', 2, 'rich_text', '<p>Poste occupé / statut actuel : ……………………………………</p><p>Expérience dans le domaine de la formation : ☐ Aucune &nbsp; ☐ Débutant &nbsp; ☐ Intermédiaire &nbsp; ☐ Avancé</p><p>Difficultés rencontrées actuellement en lien avec ce domaine : ……………………………………………………………………</p>', null, 'global'),
('questionnaire_besoins', 'objectifs_beneficiaire', 'Vos objectifs', 3, 'rich_text', '<p>Qu''attendez-vous personnellement de cette formation ? ……………………………………………………………………</p><p>Quelles compétences souhaitez-vous acquérir ou renforcer en priorité ? ……………………………………………………………………</p>', null, 'global'),
('questionnaire_besoins', 'objectifs_entreprise', 'Objectifs de l''entreprise / du financeur (si applicable)', 4, 'rich_text', '<p>Contexte professionnel ayant motivé cette formation : ……………………………………………………………………</p><p>Résultats attendus par l''employeur ou le financeur : ……………………………………………………………………</p>', null, 'global'),
('questionnaire_besoins', 'besoins_specifiques', 'Exemples de besoins fréquents dans ce domaine', 5, 'content_block_list', null, 'need_example', 'training'),
('questionnaire_besoins', 'preferences_pedagogiques', 'Préférences pédagogiques', 6, 'rich_text', '<p>Modalité préférée : ☐ Présentiel &nbsp; ☐ Distanciel &nbsp; ☐ Hybride</p><p>Rythme souhaité : ☐ Journées complètes &nbsp; ☐ Demi-journées &nbsp; ☐ Sur plusieurs semaines</p><p>Contraintes d''emploi du temps à prendre en compte : ……………………………………………………………………</p>', null, 'global'),
('questionnaire_besoins', 'accessibilite', 'Accessibilité', 7, 'rich_text', '<p>Êtes-vous en situation de handicap ou avez-vous un besoin d''aménagement particulier ? ☐ Oui &nbsp; ☐ Non</p><p>Si oui, merci de contacter {{disability_referent_name}} ({{disability_referent_email}}) pour étudier les aménagements possibles.</p>', null, 'global'),
('questionnaire_besoins', 'validation', 'Validation', 8, 'rich_text', '<p>Ce questionnaire nous permet d''adapter le programme et les modalités de la formation à votre situation. Vos réponses restent confidentielles.</p><p>Date : …………………………………… &nbsp; Signature : ……………………………………</p>', null, 'global'),

-- ---------- FICHE MOYENS PÉDAGOGIQUES, TECHNIQUES ET HUMAINS (indicateur 17) ----------
('fiche_moyens_pedagogiques', 'header', 'En-tête', 1, 'rich_text', '<p>Organisme : {{company_name}}<br/>Objet : Fiche des moyens pédagogiques, techniques et humains mobilisés<br/>Version : {{procedure_version}}</p>', null, 'global'),
('fiche_moyens_pedagogiques', 'moyens_humains', 'Moyens humains', 2, 'rich_text', '<table><thead><tr><th>Fonction</th><th>Nom</th><th>Rôle dans la prestation</th></tr></thead><tbody><tr><td>Direction / référent pédagogique</td><td>{{pedagogical_referent_name}}</td><td>Conception et supervision pédagogique</td></tr><tr><td>Référent qualité</td><td>{{quality_referent_name}}</td><td>Suivi qualité et amélioration continue</td></tr><tr><td>Référent handicap</td><td>{{disability_referent_name}}</td><td>Accueil et accompagnement des publics en situation de handicap</td></tr><tr><td>Formateur·rice (intervenant externe, le cas échéant)</td><td>{{external_trainer_name}}</td><td>{{external_trainer_discipline}}</td></tr></tbody></table><p>{{sole_practitioner_note}}</p>', null, 'global'),
('fiche_moyens_pedagogiques', 'moyens_techniques', 'Moyens techniques', 3, 'rich_text', '<ul><li>Locaux et équipements adaptés à la modalité {{training_modality}} de la formation.</li><li>Pour les sessions à distance : plateforme de visioconférence et outils numériques fournis par {{technical_provider_name}} ({{technical_provider_company}}).</li><li>Supports de formation transmis aux bénéficiaires (présentations, exercices, ressources complémentaires).</li><li>Feuille d''émargement et outils de suivi de l''assiduité.</li></ul>', null, 'global'),
('fiche_moyens_pedagogiques', 'moyens_pedagogiques', 'Méthodes pédagogiques mobilisées pour cette formation', 4, 'content_block_list', null, 'method', 'training'),
('fiche_moyens_pedagogiques', 'signature', 'Signature', 5, 'signature_block', null, null, 'global'),

-- ---------- NOS RÉSULTATS (indicateur 2) ----------
('resultats_indicateurs_qualite', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — Indicateurs de résultats</p><p>Document mis à disposition du public conformément à l''indicateur 2 du référentiel national qualité (diffusion d''indicateurs de résultats adaptés à la nature des prestations).</p>', null, 'global'),
('resultats_indicateurs_qualite', 'tableau_resultats', 'Nos indicateurs', 2, 'rich_text', '<table><thead><tr><th>Indicateur</th><th>Résultat</th><th>Objectif visé</th></tr></thead><tbody><tr><td>Taux de satisfaction des stagiaires</td><td>{{computed_learner_satisfaction}}</td><td>{{satisfaction_rate_target}}</td></tr><tr><td>Taux de satisfaction des formateurs</td><td>{{computed_trainer_satisfaction}}</td><td>{{trainer_satisfaction_rate_target}}</td></tr><tr><td>Taux de satisfaction des entreprises / financeurs</td><td>{{computed_partner_satisfaction}}</td><td>{{partner_satisfaction_rate_target}}</td></tr><tr><td>Taux de réussite</td><td>{{computed_success_rate}}</td><td>{{success_rate_target}}</td></tr><tr><td>Taux d''insertion à 6 mois</td><td>{{computed_insertion_rate}}</td><td>{{insertion_rate_target_6months}}</td></tr><tr><td>Taux de réclamations résolues</td><td>{{computed_complaints_resolved_ratio}}</td><td>100 %</td></tr></tbody></table>', null, 'global'),
('resultats_indicateurs_qualite', 'methodologie', 'Méthodologie', 3, 'rich_text', '<p>Ces indicateurs sont calculés à partir des questionnaires de satisfaction, du registre des réclamations et du suivi des sessions réalisées. Ils sont mis à jour {{watch_review_frequency}} par {{quality_referent_name}}.</p>', null, 'global'),
('resultats_indicateurs_qualite', 'publication', 'Publication', 4, 'rich_text', '<p>Ces résultats sont consultables sur {{company_website}} et communiqués sur demande à toute personne intéressée, conformément à l''obligation d''information du public (indicateurs 1 et 2 du référentiel national qualité).</p>', null, 'global'),

-- ---------- FORMULAIRE DE RÉCLAMATION (indicateur 31) ----------
('formulaire_reclamation', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — Formulaire de réclamation</p><p>Ce formulaire permet à tout stagiaire, entreprise, financeur, formateur ou partenaire de signaler un dysfonctionnement ou d''exprimer une insatisfaction.</p>', null, 'global'),
('formulaire_reclamation', 'profil', 'Votre profil', 2, 'rich_text', '<p>☐ Stagiaire &nbsp; ☐ Entreprise &nbsp; ☐ Financeur &nbsp; ☐ Formateur &nbsp; ☐ Partenaire &nbsp; ☐ Autre : ……………………</p><p>Nom et prénom : …………………………………… &nbsp; Email : …………………………………… &nbsp; Téléphone : ……………………………………</p><p>Formation / session concernée : …………………………………… &nbsp; Date des faits : ……………………………………</p>', null, 'global'),
('formulaire_reclamation', 'description', 'Votre réclamation', 3, 'rich_text', '<p>Objet de la réclamation : ……………………………………………………………………</p><p>Description détaillée : ……………………………………………………………………</p><p>……………………………………………………………………</p><p>……………………………………………………………………</p><p>Mesures déjà tentées pour résoudre la situation (le cas échéant) : ……………………………………………………………………</p><p>Niveau d''urgence perçu : ☐ Faible &nbsp; ☐ Moyen &nbsp; ☐ Élevé</p>', null, 'global'),
('formulaire_reclamation', 'rgpd_delais', 'Consentement et délais', 4, 'rich_text', '<p>☐ J''accepte que les informations transmises soient utilisées par {{company_name}} dans le seul cadre du traitement de cette réclamation, conformément au RGPD ({{dpo_contact_email}}).</p><p>Un accusé de réception vous sera adressé sous {{complaint_ack_delay}}. Une réponse motivée vous sera communiquée sous {{complaint_response_delay}}.</p><p>Date : …………………………………… &nbsp; Signature : ……………………………………</p>', null, 'global'),

-- ---------- ACCUSÉ DE RÉCEPTION D'UNE RÉCLAMATION (indicateur 31) ----------
('accuse_reception_reclamation', 'content', 'Accusé de réception', 1, 'rich_text', '<p>{{company_name}} — {{address}}</p><p>{{organization_city}}, le {{generated_date}}</p><p><strong>Objet : Accusé de réception de votre réclamation</strong></p><p>Madame, Monsieur,</p><p>Nous accusons réception de votre réclamation transmise via notre formulaire de réclamation.</p><p>Conformément à notre procédure qualité, nous nous engageons à vous apporter une réponse motivée sous {{complaint_response_delay}} à compter de ce jour.</p><p>Votre dossier est traité par {{quality_referent_name}} ({{complaints_email}}).</p><p>En cas de désaccord persistant à l''issue de notre réponse, vous disposez d''un droit à saisir un médiateur de la consommation.</p><p>Nous vous prions d''agréer, Madame, Monsieur, l''expression de nos salutations distinguées.</p><p>{{director_name}}<br/>{{company_name}}</p>', null, 'global'),

-- ---------- QUESTIONNAIRE DE SATISFACTION (indicateur 30) ----------
('questionnaire_satisfaction', 'header', 'En-tête', 1, 'rich_text', '<p>{{company_name}} — Questionnaire de satisfaction</p><p>Formation suivie : <strong>{{training_name}}</strong> — du {{training_start_date}} au {{training_end_date}}</p><p>Nom (facultatif) : …………………………………… &nbsp; Vous pouvez répondre de façon anonyme.</p><p>Pour chaque item, merci de noter de 1 (très insatisfait) à 5 (très satisfait).</p>', null, 'global'),
('questionnaire_satisfaction', 'organisation', 'Organisation et logistique', 2, 'rich_text', '<table><thead><tr><th>Critère</th><th>Note (1 à 5)</th></tr></thead><tbody><tr><td>Qualité de l''accueil</td><td></td></tr><tr><td>Locaux / plateforme à distance</td><td></td></tr><tr><td>Respect des horaires</td><td></td></tr><tr><td>Communication avant la formation (convocation, informations pratiques)</td><td></td></tr></tbody></table>', null, 'global'),
('questionnaire_satisfaction', 'contenu_animation', 'Contenu et animation', 3, 'rich_text', '<table><thead><tr><th>Critère</th><th>Note (1 à 5)</th></tr></thead><tbody><tr><td>Clarté des objectifs annoncés</td><td></td></tr><tr><td>Qualité des supports pédagogiques</td><td></td></tr><tr><td>Pédagogie et disponibilité du formateur / de la formatrice</td><td></td></tr><tr><td>Adéquation du contenu avec vos besoins</td><td></td></tr></tbody></table>', null, 'global'),
('questionnaire_satisfaction', 'impact', 'Impact de la formation', 4, 'rich_text', '<p>Pensez-vous pouvoir appliquer rapidement ce que vous avez appris ? ☐ Oui &nbsp; ☐ Non &nbsp; ☐ Partiellement</p><p>Cette formation a-t-elle répondu à vos attentes ? ☐ Oui &nbsp; ☐ Non &nbsp; ☐ Partiellement</p>', null, 'global'),
('questionnaire_satisfaction', 'recommandation', 'Recommandation', 5, 'rich_text', '<p>Recommanderiez-vous cette formation ? ☐ Oui &nbsp; ☐ Non</p><p>Note globale sur 20 : …… / 20</p>', null, 'global'),
('questionnaire_satisfaction', 'remarques', 'Remarques libres', 6, 'rich_text', '<p>……………………………………………………………………</p><p>……………………………………………………………………</p><p>……………………………………………………………………</p>', null, 'global'),
('questionnaire_satisfaction', 'mention_scoring', 'Mention', 7, 'rich_text', '<p class="empty">Score calculé sur 32 points puis converti en note sur 20 — utilisé pour le suivi de l''objectif de satisfaction ({{satisfaction_rate_target}} visé, cf. document "Nos résultats").</p>', null, 'global');
