-- Migration 0021 : indicateur 27 (sous-traitance), lot 2 des gaps Phase 5,
-- item 11. Jusqu'ici, la sélection et le contrat de sous-traitance
-- n'existaient qu'en paragraphe narratif dans procedure_selection_sous_traitants
-- (qui reste en place, inchangée). Un vrai audit veut voir : (a) une grille de
-- notation REMPLIE pour un candidat précis, avec un score et une décision, et
-- (b) un contrat de sous-traitance signable à part entière — pas seulement un
-- exemple de clause noyé dans une procédure.
--
-- Contenu réel repris du dossier d'audit de Nora (Grille de sélection des
-- sous-traitants.pdf : 6 critères pondérés, seuil 70 % ; Contrat de
-- sous-traitance d'enseignement.pdf : 12 articles), généricisé.
--
-- Les champs propres au sous-traitant (identité, SIRET, taux horaire, dates
-- de mission) ne sont pas encore stockés en base (pas de table dédiée) :
-- laissés en blancs à remplir à la main, comme pour les grilles d'entretien
-- (migration 0020) — seuls les champs déjà connus du système (organisme,
-- dirigeant, formation, lieu/modalité de la session, ville, juridiction)
-- sont interpolés automatiquement.

insert into document_templates (id, label, category_scope, applicable_when, linked_indicator_numbers, folder_group, sort_order, is_active) values
('grille_selection_sous_traitants', 'Grille de sélection des sous-traitants', 'all', '{}'::jsonb, ARRAY[27], '06_Procedures', 42, true),
('contrat_sous_traitance', 'Contrat de sous-traitance d''enseignement', 'all', '{}'::jsonb, ARRAY[27], '06_Procedures', 43, true);

insert into document_template_sections (document_template_id, code, title, sort_order, content_type, html_template, source_content_block_type, content_block_scope) values

-- ---------- GRILLE DE SÉLECTION DES SOUS-TRAITANTS (notée) ----------
('grille_selection_sous_traitants', 'header', 'Informations générales', 1, 'rich_text', '<p>{{company_name}} — Grille de sélection des sous-traitants</p><p>Objectif : évaluer la conformité d''un formateur ou prestataire externe avant contractualisation.</p><p>Candidat évalué : ……………………………………………………<br/>Formation concernée : {{training_name}}<br/>Date de l''évaluation : {{generated_date}} &nbsp; Évaluateur : {{quality_referent_name}}</p>', null, 'global'),
('grille_selection_sous_traitants', 'grille', 'Grille de notation', 2, 'rich_text', '<table><thead><tr><th>Critère</th><th>Description</th><th>Pondération</th><th>Seuil minimal</th><th>Score obtenu</th></tr></thead><tbody><tr><td>Diplôme / Certification</td><td>Titulaire d''un diplôme ou d''une certification en lien avec le domaine enseigné.</td><td>30 %</td><td>Oui</td><td></td></tr><tr><td>Expérience professionnelle</td><td>Minimum 3 ans d''expérience dans le secteur ou la spécialité visée.</td><td>25 %</td><td>3 ans</td><td></td></tr><tr><td>Compétences pédagogiques</td><td>Expérience de formation, animation de groupe, maîtrise des objectifs pédagogiques.</td><td>15 %</td><td>Oui</td><td></td></tr><tr><td>Références professionnelles</td><td>Présentation de 2 références vérifiables (organismes, écoles, entreprises).</td><td>15 %</td><td>2</td><td></td></tr><tr><td>Maîtrise des outils numériques &amp; IA</td><td>Connaissance des outils EdTech, IA, Canva, LMS, etc.</td><td>10 %</td><td>Oui</td><td></td></tr><tr><td>Disponibilité et respect des délais</td><td>Capacité à suivre le calendrier et fournir les supports à temps.</td><td>5 %</td><td>Oui</td><td></td></tr><tr><td><strong>TOTAL</strong></td><td>Seuil minimum requis pour validation : <strong>70 %</strong></td><td>100 %</td><td></td><td><strong></strong></td></tr></tbody></table>', null, 'global'),
('grille_selection_sous_traitants', 'decision', 'Décision', 3, 'rich_text', '<p>☐ Candidature retenue (score ≥ 70 %) &nbsp; ☐ Candidature rejetée (score &lt; 70 %) &nbsp; ☐ Réserve — compléments demandés</p><p>Commentaire : ……………………………………………………………………</p>', null, 'global'),
('grille_selection_sous_traitants', 'validation', 'Validation', 4, 'signature_block', null, null, 'global'),

-- ---------- CONTRAT DE SOUS-TRAITANCE D'ENSEIGNEMENT (signable, 12 articles) ----------
('contrat_sous_traitance', 'header', 'Entre les soussignés', 1, 'rich_text', '<p><strong>CONTRAT DE SOUS-TRAITANCE D''ENSEIGNEMENT</strong></p><p>Entre les soussignés :</p><p>1) {{company_name}}, dont le siège social est situé à {{address}}, représenté par {{director_name}} — ci-après désigné « l''Organisme de Formation ».</p><p>2) …………………………………………………… (nom, prénom du formateur), né(e) le ……………, domicilié(e) à ……………………………………………………, immatriculé(e) sous le n° SIRET …………………… — ci-après désigné(e) « le Formateur ».</p><p>L''Organisme de Formation et le Formateur sont appelés collectivement les « Parties ».</p>', null, 'global'),
('contrat_sous_traitance', 'nature_objet', 'Article 1 — Nature du contrat / Article 2 — Objet', 2, 'rich_text', '<p><strong>Article 1 – Nature du contrat</strong><br/>Le présent contrat est conclu dans le cadre d''une prestation de formation ponctuelle réalisée par le Formateur au bénéfice de {{company_name}}. Cette prestation intervient à titre indépendant.</p><p><strong>Article 2 – Objet du contrat</strong><br/>Le Formateur dispense la formation suivante aux apprenants de {{company_name}} :<br/>Formation concernée : {{training_name}}<br/>Public / groupe concerné : ……………………………………………………</p>', null, 'global'),
('contrat_sous_traitance', 'duree_lieu', 'Article 3 — Durée / Article 4 — Lieu d''exécution', 3, 'rich_text', '<p><strong>Article 3 – Durée du contrat</strong><br/>Le contrat est conclu pour la période allant du …………… au ……………. Nombre d''heures prévisionnel : ……… heures. Le contrat est à durée déterminée et ne pourra être renouvelé tacitement.</p><p><strong>Article 4 – Lieu d''exécution</strong><br/>Les prestations seront réalisées {{training_location}} ou dans tout autre lieu convenu par les Parties ({{training_modality}}).</p>', null, 'global'),
('contrat_sous_traitance', 'remuneration', 'Article 5 — Rémunération', 4, 'rich_text', '<p><strong>Article 5 – Rémunération</strong><br/>Pour les formations dispensées, {{company_name}} rémunère le Formateur à hauteur de : ……… € HT/heure. Cette rémunération inclut le temps de préparation, correction et suivi pédagogique.</p>', null, 'global'),
('contrat_sous_traitance', 'obligations', 'Article 6 — Obligations du Formateur / Article 7 — Obligations de l''Organisme', 5, 'rich_text', '<p><strong>Article 6 – Obligations du Formateur</strong><br/>Le Formateur s''engage à respecter les référentiels pédagogiques, le règlement intérieur, les obligations Qualiopi, ainsi que les consignes de {{company_name}}. Il doit notamment : participer aux réunions pédagogiques, assurer les évaluations, respecter le calendrier, et remettre les documents pédagogiques nécessaires.</p><p><strong>Article 7 – Obligations de l''Organisme de Formation</strong><br/>{{company_name}} s''engage à fournir au Formateur tous les éléments nécessaires (planning, supports administratifs, émargements, questionnaires de satisfaction) et à assurer la gestion administrative et logistique de la formation.</p>', null, 'global'),
('contrat_sous_traitance', 'modalites_financieres', 'Article 8 — Modalités financières', 6, 'rich_text', '<p><strong>Article 8 – Modalités financières</strong><br/>Le paiement sera effectué à réception de facture mensuelle, au plus tard le …… de chaque mois. Seules les heures réellement effectuées pourront être facturées.</p>', null, 'global'),
('contrat_sous_traitance', 'independance_confidentialite', 'Article 9 — Indépendance / Article 10 — Non-concurrence et confidentialité', 7, 'rich_text', '<p><strong>Article 9 – Indépendance des parties</strong><br/>Le présent contrat ne crée aucun lien de subordination entre les Parties. Le Formateur reste indépendant.</p><p><strong>Article 10 – Non-concurrence et confidentialité</strong><br/>Le Formateur s''engage à ne pas démarcher directement les clients de {{company_name}}, à préserver la confidentialité des informations et à respecter la propriété intellectuelle des contenus pédagogiques.</p>', null, 'global'),
('contrat_sous_traitance', 'resiliation_tribunal', 'Article 11 — Résiliation / Article 12 — Tribunal compétent', 8, 'rich_text', '<p><strong>Article 11 – Résiliation</strong><br/>Chaque Partie pourra mettre fin au contrat après une mise en demeure restée infructueuse pendant 15 jours. {{company_name}} pourra résilier immédiatement en cas de manquement grave (absences répétées, non-respect des obligations).</p><p><strong>Article 12 – Tribunal compétent</strong><br/>Le présent contrat est régi par le droit français. En cas de litige, le {{jurisdiction}} sera compétent.</p>', null, 'global'),
('contrat_sous_traitance', 'signatures', 'Signatures', 9, 'rich_text', '<p>Fait à {{organization_city}}, le {{generated_date}}</p><table style="width:100%; margin-top:8pt;"><tbody><tr><td style="width:50%; vertical-align:top;">Pour {{company_name}}<br/>{{director_name}}<br/><br/>Signature :<br/><br/><br/></td><td style="width:50%; vertical-align:top;">Le Formateur<br/><br/>Signature :<br/><br/><br/></td></tr></tbody></table>', null, 'global');
